-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260905190100_rls_staffing). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- ClientContract (org)
ALTER TABLE "ClientContract" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ClientContract" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ClientContract";
DROP POLICY IF EXISTS tenant_access ON "ClientContract";
DROP POLICY IF EXISTS tenant_read ON "ClientContract";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ClientContract" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ClientContract";
CREATE POLICY tenant_access ON "ClientContract" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- Engagement (org)
ALTER TABLE "Engagement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Engagement" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Engagement";
DROP POLICY IF EXISTS tenant_access ON "Engagement";
DROP POLICY IF EXISTS tenant_read ON "Engagement";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Engagement" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Engagement";
CREATE POLICY tenant_access ON "Engagement" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- FeeStructure (org)
ALTER TABLE "FeeStructure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeeStructure" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "FeeStructure";
DROP POLICY IF EXISTS tenant_access ON "FeeStructure";
DROP POLICY IF EXISTS tenant_read ON "FeeStructure";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "FeeStructure" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "FeeStructure";
CREATE POLICY tenant_access ON "FeeStructure" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- Placement (org)
ALTER TABLE "Placement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Placement" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Placement";
DROP POLICY IF EXISTS tenant_access ON "Placement";
DROP POLICY IF EXISTS tenant_read ON "Placement";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Placement" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Placement";
CREATE POLICY tenant_access ON "Placement" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- PlacementInvoice (org)
ALTER TABLE "PlacementInvoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlacementInvoice" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "PlacementInvoice";
DROP POLICY IF EXISTS tenant_access ON "PlacementInvoice";
DROP POLICY IF EXISTS tenant_read ON "PlacementInvoice";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "PlacementInvoice" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "PlacementInvoice";
CREATE POLICY tenant_access ON "PlacementInvoice" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- RepresentationConsent (custom)
ALTER TABLE "RepresentationConsent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RepresentationConsent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "RepresentationConsent";
DROP POLICY IF EXISTS tenant_access ON "RepresentationConsent";
DROP POLICY IF EXISTS tenant_read ON "RepresentationConsent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "RepresentationConsent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "RepresentationConsent";
CREATE POLICY tenant_access ON "RepresentationConsent" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));
CREATE POLICY tenant_read ON "RepresentationConsent" FOR SELECT TO app_tenant USING (("organizationId" = ANY (app_member_organization_ids()) OR "candidateUserId" = app_current_user_id()));

-- StaffingJurisdictionRule (reference)
ALTER TABLE "StaffingJurisdictionRule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StaffingJurisdictionRule" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "StaffingJurisdictionRule";
DROP POLICY IF EXISTS tenant_access ON "StaffingJurisdictionRule";
DROP POLICY IF EXISTS tenant_read ON "StaffingJurisdictionRule";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "StaffingJurisdictionRule" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "StaffingJurisdictionRule";
CREATE POLICY tenant_read ON "StaffingJurisdictionRule" FOR SELECT TO app_tenant USING (true);
