import { Document, Packer, Paragraph, TextRun } from 'docx';
import JSZip from 'jszip';
import type { DocumentModel } from './model';
import type { RenderOptions } from './render-pdf';

/**
 * Stage 09 — the DOCX renderer.
 *
 * Paragraphs, bold runs and simple bullets only: no tables, text boxes,
 * headers/footers or images, because those are exactly what résumé parsers
 * mangle. The `docx` library stamps "now" into `docProps/core.xml` and the
 * zip container stamps every entry with the wall clock, so the raw package
 * is re-packed canonically: entries sorted, a fixed entry timestamp, and
 * the caller's `createdAt` as the document's created/modified date. Same
 * model, same `createdAt` → same bytes (tested).
 */
export async function renderDocx(model: DocumentModel, opts: RenderOptions): Promise<Buffer> {
  const children: Paragraph[] = [];
  model.header.forEach((line, i) => {
    children.push(new Paragraph({ children: [new TextRun({ text: line, bold: i === 0, size: i === 0 ? 32 : 20 })], spacing: { after: 60 } }));
  });
  for (const section of model.sections) {
    if (section.heading) children.push(new Paragraph({ children: [new TextRun({ text: section.heading, bold: true, size: 22 })], spacing: { before: 240, after: 80 } }));
    for (const p of section.paragraphs ?? []) children.push(paragraphWithBreaks(p));
    for (const b of section.bullets ?? []) children.push(new Paragraph({ text: b, bullet: { level: 0 } }));
    for (const e of section.entries ?? []) {
      children.push(new Paragraph({ children: [new TextRun({ text: e.heading, bold: true })], spacing: { before: 160 } }));
      if (e.sub) children.push(new Paragraph({ children: [new TextRun({ text: e.sub, color: '555555', size: 18 })] }));
      for (const b of e.bullets) children.push(new Paragraph({ text: b, bullet: { level: 0 } }));
    }
  }
  const doc = new Document({
    creator: opts.author,
    title: model.title,
    description: 'Generated by JobPilot',
    styles: { default: { document: { run: { font: 'Arial', size: 20 } } } },
    sections: [{ properties: {}, children }],
  });
  const raw = await Packer.toBuffer(doc);
  return canonicalDocx(raw, opts.createdAt);
}

/** A block with line breaks (an address, a signature) is one paragraph with soft breaks. */
function paragraphWithBreaks(block: string): Paragraph {
  const lines = block.split('\n');
  return new Paragraph({ children: lines.map((l, i) => (i === 0 ? new TextRun(l) : new TextRun({ text: l, break: 1 }))), spacing: { after: 120 } });
}

/** A local-time constructor: DOS timestamps in a zip are local time, so this is 1980-01-01 00:00 whatever the server's zone. */
const ZIP_ENTRY_DATE = new Date(1980, 0, 1, 0, 0, 0);

/** Re-pack a docx deterministically and pin its core dates to `createdAt`. */
export async function canonicalDocx(raw: Buffer, createdAt: Date): Promise<Buffer> {
  const zip = await JSZip.loadAsync(raw);
  const out = new JSZip();
  const stamp = createdAt.toISOString().replace(/\.\d{3}Z$/, 'Z');
  for (const name of Object.keys(zip.files).sort()) {
    const entry = zip.files[name];
    if (entry.dir) continue;
    let body = await entry.async('nodebuffer');
    if (name === 'docProps/core.xml') {
      body = Buffer.from(
        body
          .toString('utf8')
          .replace(/(<dcterms:created[^>]*>)[^<]*(<\/dcterms:created>)/, `$1${stamp}$2`)
          .replace(/(<dcterms:modified[^>]*>)[^<]*(<\/dcterms:modified>)/, `$1${stamp}$2`),
        'utf8',
      );
    }
    out.file(name, body, { date: ZIP_ENTRY_DATE, createFolders: false });
  }
  return out.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE', compressionOptions: { level: 9 }, platform: 'UNIX' });
}

/** The document text as a parser sees it: paragraphs to lines, tags stripped, entities decoded. Parse-back only. */
export async function extractDocxText(docx: Buffer): Promise<string> {
  const zip = await JSZip.loadAsync(docx);
  const xml = await zip.file('word/document.xml')?.async('string');
  if (!xml) return '';
  return xml
    .replace(/<w:tab\s*\/>/g, '\t')
    .replace(/<w:br\s*\/>/g, '\n')
    .replace(/<\/w:p>/g, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&apos;/g, "'");
}
