import nextCoreWebVitals from 'eslint-config-next/core-web-vitals';
import nextTypescript from 'eslint-config-next/typescript';

/**
 * ESLint configuration — Stage 00.
 *
 * WHY THIS EXISTS AND WHAT IT DELIBERATELY DOES NOT DO
 * ----------------------------------------------------
 * Before Stage 00, ESLint was neither installed nor configured. `next.config.mjs`
 * set `eslint: { ignoreDuringBuilds: true }`, which reads as "lint is skipped at
 * build time" — but lint had in fact never run at all, and `npm run lint`
 * (`next lint`) dropped into an interactive setup prompt and exited 1. Putting
 * that into CI would have hung the runner.
 *
 * So there is no historical lint debt to "keep down": there is an unmeasured
 * first-run backlog across the whole codebase. Turning every rule on at once
 * would produce a blocking gate nobody can pass, which in practice means the gate
 * gets disabled and lint dies a second time.
 *
 * The approach instead:
 *   1. Configure lint so it runs non-interactively and deterministically.
 *   2. Measure the real violation count and commit it as a baseline
 *      (docs/programme/LINT_BASELINE.md).
 *   3. Report — not block — in CI for now.
 *   4. Ratchet: fix by rule class, and flip each cleaned rule to "error".
 *
 * `next lint` is NOT used. It was deprecated in Next 15 and is REMOVED in Next
 * 16, which Stage 01 upgraded to under ADR-0017 — so `npm run lint` invokes
 * eslint directly and kept working across that upgrade, which was the point of
 * choosing it. This also permanently removes the interactive prompt.
 *
 * The configs are imported as NATIVE FLAT CONFIG. eslint-config-next 15 was
 * eslintrc-shaped and needed the `FlatCompat` shim; version 16 ships real flat
 * config arrays, and feeding those back through FlatCompat throws
 * "Converting circular structure to JSON". The shim and its `@eslint/eslintrc`
 * dependency are therefore gone.
 */

const config = [
  {
    // Generated, vendored, or not source. `importMap.js` and `payload-types.ts`
    // are regenerated by the Payload CLI and are verified for drift by CI
    // instead — linting them would fail on code we do not author.
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'build/**',
      'dist/**',
      'storage/**',
      'media/**',
      'next-env.d.ts',
      'src/app/(payload)/admin/importMap.js',
      'src/payload-types.ts',
    ],
  },
  ...nextCoreWebVitals,
  ...nextTypescript,
  {
    rules: {
      // Deliberately downgraded to warnings for the Stage 00 baseline so the
      // measured count is visible without blocking. Each is ratcheted to
      // "error" as its class is remediated — see docs/programme/LINT_BASELINE.md.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],

      /**
       * Surfaced by the Next 16 upgrade (ADR-0017), not by new code.
       *
       * eslint-config-next 16 enables `react-hooks/set-state-in-effect`, which
       * flags six pre-existing call sites. Each was read before this rule was
       * relaxed, and none is a defect:
       *
       *   - `usePrefersReducedMotion` and the `mounted` flag in drawer.tsx set
       *     state from an effect because `window.matchMedia` and hydration
       *     status CANNOT be read during a server render. This is the standard
       *     SSR-safe pattern; the cost is one extra render on mount.
       *   - The drawer's `rendered`/`entered` pair deliberately sequences
       *     renders so the panel animates from an off-screen start position.
       *     Setting state in the effect is the mechanism, not an oversight.
       *   - data-table.tsx clamps the page when a filter shortens the list, and
       *     resets page/row when the query or sort changes. These two ARE
       *     improvable — the clamp is derivable during render — and are the
       *     real remediation target.
       *
       * They stay VISIBLE as warnings rather than being disabled: every run
       * prints them and the ratchet counts them. They are not refactored here
       * because rewriting animation and pagination behaviour during a security
       * stage is scope creep against components with no test coverage.
       * Tracked in docs/programme/LINT_BASELINE.md.
       */
      'react-hooks/set-state-in-effect': 'warn',
    },
  },
  {
    // The Payload CLI wrapper and config scripts run in Node, not the browser.
    files: ['scripts/**/*.mjs', '*.config.{mjs,ts}'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    /**
     * THE PROVIDER PATTERN'S LAZY `require()` IS DELIBERATE — NOT DEBT.
     *
     * `src/lib/providers/*` resolves a real adapter (Anthropic, Adzuna, Stripe,
     * PayPal) through a lazy `require()` precisely so the SDK is never loaded in
     * a deployment that does not use it. That is what lets a clean clone boot
     * with zero configuration, and it is recorded as a must-preserve convention
     * in docs/programme/GAP_ANALYSIS.md Part 5 and CLAUDE.md.
     *
     * A static `import` here would defeat it: the module graph would pull every
     * provider SDK into every deployment. So the rule is scoped off for these
     * files with a stated reason, rather than the code being "fixed" to satisfy
     * a lint default that does not know the design intent.
     *
     * This is the only rule exemption in this configuration. It is narrow (one
     * directory), documented, and reviewable.
     */
    files: ['src/lib/providers/**/*.ts'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
];

export default config;
