import { FlatCompat } from '@eslint/eslintrc';

/**
 * ESLint configuration — Stage 00.
 *
 * WHY THIS EXISTS AND WHAT IT DELIBERATELY DOES NOT DO
 * ----------------------------------------------------
 * Before Stage 00, ESLint was neither installed nor configured. `next.config.mjs`
 * set `eslint: { ignoreDuringBuilds: true }`, which reads as "lint is skipped at
 * build time" — but lint had in fact never run at all, and `npm run lint`
 * (`next lint`) dropped into an interactive setup prompt and exited 1. Putting
 * that into CI would have hung the runner.
 *
 * So there is no historical lint debt to "keep down": there is an unmeasured
 * first-run backlog across the whole codebase. Turning every rule on at once
 * would produce a blocking gate nobody can pass, which in practice means the gate
 * gets disabled and lint dies a second time.
 *
 * The approach instead:
 *   1. Configure lint so it runs non-interactively and deterministically.
 *   2. Measure the real violation count and commit it as a baseline
 *      (docs/programme/LINT_BASELINE.md).
 *   3. Report — not block — in CI for now.
 *   4. Ratchet: fix by rule class, and flip each cleaned rule to "error".
 *
 * `next lint` is NOT used. It is deprecated in Next 15 and removed in Next 16,
 * which Stage 01 upgrades to under ADR-0017 — so `npm run lint` invokes eslint
 * directly and will keep working across that upgrade. This also permanently
 * removes the interactive prompt.
 */
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

const config = [
  {
    // Generated, vendored, or not source. `importMap.js` and `payload-types.ts`
    // are regenerated by the Payload CLI and are verified for drift by CI
    // instead — linting them would fail on code we do not author.
    ignores: [
      'node_modules/**',
      '.next/**',
      'out/**',
      'build/**',
      'dist/**',
      'storage/**',
      'media/**',
      'next-env.d.ts',
      'src/app/(payload)/admin/importMap.js',
      'src/payload-types.ts',
    ],
  },
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    rules: {
      // Deliberately downgraded to warnings for the Stage 00 baseline so the
      // measured count is visible without blocking. Each is ratcheted to
      // "error" as its class is remediated — see docs/programme/LINT_BASELINE.md.
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
    },
  },
  {
    // The Payload CLI wrapper and config scripts run in Node, not the browser.
    files: ['scripts/**/*.mjs', '*.config.{mjs,ts}'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
  {
    /**
     * THE PROVIDER PATTERN'S LAZY `require()` IS DELIBERATE — NOT DEBT.
     *
     * `src/lib/providers/*` resolves a real adapter (Anthropic, Adzuna, Stripe,
     * PayPal) through a lazy `require()` precisely so the SDK is never loaded in
     * a deployment that does not use it. That is what lets a clean clone boot
     * with zero configuration, and it is recorded as a must-preserve convention
     * in docs/programme/GAP_ANALYSIS.md Part 5 and CLAUDE.md.
     *
     * A static `import` here would defeat it: the module graph would pull every
     * provider SDK into every deployment. So the rule is scoped off for these
     * files with a stated reason, rather than the code being "fixed" to satisfy
     * a lint default that does not know the design intent.
     *
     * This is the only rule exemption in this configuration. It is narrow (one
     * directory), documented, and reviewable.
     */
    files: ['src/lib/providers/**/*.ts'],
    rules: { '@typescript-eslint/no-require-imports': 'off' },
  },
];

export default config;
