-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903100100_rls_taxonomy_tables). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- CareerPath (reference)
ALTER TABLE "CareerPath" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CareerPath" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CareerPath";
DROP POLICY IF EXISTS tenant_access ON "CareerPath";
DROP POLICY IF EXISTS tenant_read ON "CareerPath";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CareerPath" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CareerPath";
CREATE POLICY tenant_read ON "CareerPath" FOR SELECT TO app_tenant USING (true);

-- Occupation (reference)
ALTER TABLE "Occupation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Occupation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Occupation";
DROP POLICY IF EXISTS tenant_access ON "Occupation";
DROP POLICY IF EXISTS tenant_read ON "Occupation";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Occupation" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Occupation";
CREATE POLICY tenant_read ON "Occupation" FOR SELECT TO app_tenant USING (true);

-- OccupationCode (reference)
ALTER TABLE "OccupationCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OccupationCode" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "OccupationCode";
DROP POLICY IF EXISTS tenant_access ON "OccupationCode";
DROP POLICY IF EXISTS tenant_read ON "OccupationCode";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "OccupationCode" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "OccupationCode";
CREATE POLICY tenant_read ON "OccupationCode" FOR SELECT TO app_tenant USING (true);

-- OccupationLabel (reference)
ALTER TABLE "OccupationLabel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OccupationLabel" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "OccupationLabel";
DROP POLICY IF EXISTS tenant_access ON "OccupationLabel";
DROP POLICY IF EXISTS tenant_read ON "OccupationLabel";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "OccupationLabel" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "OccupationLabel";
CREATE POLICY tenant_read ON "OccupationLabel" FOR SELECT TO app_tenant USING (true);

-- OccupationSkill (reference)
ALTER TABLE "OccupationSkill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OccupationSkill" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "OccupationSkill";
DROP POLICY IF EXISTS tenant_access ON "OccupationSkill";
DROP POLICY IF EXISTS tenant_read ON "OccupationSkill";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "OccupationSkill" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "OccupationSkill";
CREATE POLICY tenant_read ON "OccupationSkill" FOR SELECT TO app_tenant USING (true);

-- Region (reference)
ALTER TABLE "Region" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Region" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Region";
DROP POLICY IF EXISTS tenant_access ON "Region";
DROP POLICY IF EXISTS tenant_read ON "Region";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Region" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Region";
CREATE POLICY tenant_read ON "Region" FOR SELECT TO app_tenant USING (true);

-- RegionLabel (reference)
ALTER TABLE "RegionLabel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RegionLabel" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "RegionLabel";
DROP POLICY IF EXISTS tenant_access ON "RegionLabel";
DROP POLICY IF EXISTS tenant_read ON "RegionLabel";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "RegionLabel" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "RegionLabel";
CREATE POLICY tenant_read ON "RegionLabel" FOR SELECT TO app_tenant USING (true);

-- SkillLabel (reference)
ALTER TABLE "SkillLabel" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SkillLabel" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SkillLabel";
DROP POLICY IF EXISTS tenant_access ON "SkillLabel";
DROP POLICY IF EXISTS tenant_read ON "SkillLabel";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SkillLabel" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SkillLabel";
CREATE POLICY tenant_read ON "SkillLabel" FOR SELECT TO app_tenant USING (true);

-- SkillMapping (reference)
ALTER TABLE "SkillMapping" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SkillMapping" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SkillMapping";
DROP POLICY IF EXISTS tenant_access ON "SkillMapping";
DROP POLICY IF EXISTS tenant_read ON "SkillMapping";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SkillMapping" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SkillMapping";
CREATE POLICY tenant_read ON "SkillMapping" FOR SELECT TO app_tenant USING (true);

-- TaxonomyDataset (reference)
ALTER TABLE "TaxonomyDataset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaxonomyDataset" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "TaxonomyDataset";
DROP POLICY IF EXISTS tenant_access ON "TaxonomyDataset";
DROP POLICY IF EXISTS tenant_read ON "TaxonomyDataset";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "TaxonomyDataset" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "TaxonomyDataset";
CREATE POLICY tenant_read ON "TaxonomyDataset" FOR SELECT TO app_tenant USING (true);
