-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260905200100_rls_enterprise). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- ScimToken (system)
ALTER TABLE "ScimToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ScimToken" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ScimToken";
DROP POLICY IF EXISTS tenant_access ON "ScimToken";
DROP POLICY IF EXISTS tenant_read ON "ScimToken";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ScimToken" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ScimToken";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- SsoConnection (system)
ALTER TABLE "SsoConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SsoConnection" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SsoConnection";
DROP POLICY IF EXISTS tenant_access ON "SsoConnection";
DROP POLICY IF EXISTS tenant_read ON "SsoConnection";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SsoConnection" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SsoConnection";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)
