/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = {
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The key owner's profile summary */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Lightweight profile edits: name, city, headline, application mode (v1.1) */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/v1/recommendations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Best open, eligible, not-yet-acted-on matches, score first */
        get: operations["listRecommendations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Jobs the caller's agents matched, with filters */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One matched posting with its text and the caller's eligibility verdict */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/matches/{matchId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Why a posting scored what it did */
        get: operations["getMatchAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's applications, newest first */
        get: operations["listApplications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/applications/{applicationId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The whole folder: history, contacts, interviews, assessments, follow-ups, documents, prepared package, completeness */
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/applications/{applicationId}/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record that the applicant submitted the prepared application on the employer's form */
        post: operations["confirmApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/applications/{applicationId}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** The applicant instructs a submission through an employer-authorised ATS after review */
        post: operations["submitApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every interview across the caller's folders, soonest first */
        get: operations["listInterviews"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** What happened, newest first; ids and fixed messages only */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/analytics/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The dashboard numbers in one request */
        get: operations["getAnalyticsSummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/ats-rulesets/{platform}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The active ruleset for an ATS platform */
        get: operations["getAtsRuleset"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's signed-in devices (v1.1) */
        get: operations["listDeviceSessions"];
        put?: never;
        /** Sign in on a device: mint the bearer key the app holds (v1.1) */
        post: operations["createDeviceSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign out: revoke the key that made the request (v1.1) */
        delete: operations["revokeCurrentDeviceSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Sign one of the caller's other devices out (v1.1) */
        delete: operations["revokeDeviceSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Every consent purpose with its current state (v1.1) */
        get: operations["listConsents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/consents/{purpose}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Grant or withdraw one purpose (v1.1) */
        put: operations["setConsent"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/jobs/{jobId}/saved": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save a matched posting; idempotent (v1.1) */
        put: operations["saveJob"];
        post?: never;
        /** Unsave; idempotent (v1.1) */
        delete: operations["unsaveJob"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/saved-jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The caller's saved postings, newest first (v1.1) */
        get: operations["listSavedJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/applications/{applicationId}/documents/{documentId}/link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** A ten-minute signed link to one document version in the folder (v1.1) */
        post: operations["createDocumentLink"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/evidence": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The vault's claims, read-only (v1.1) */
        get: operations["listEvidence"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
};
export type webhooks = Record<string, never>;
export type components = {
    schemas: {
        Error: {
            error: {
                /** @enum {string} */
                type: "authentication_error" | "permission_error" | "invalid_request_error" | "not_found_error" | "rate_limit_error" | "api_error";
                /** @enum {string} */
                code: "unauthorized" | "insufficient_scope" | "invalid_request" | "not_found" | "rate_limited" | "internal_error" | "unavailable";
                message: string;
                param?: string;
            };
        };
        Me: {
            /** @constant */
            object: "me";
            id: string;
            fullName: string;
            email: string;
            /** @enum {string} */
            country: "CA" | "US";
            city: string | null;
            headline: string | null;
            /**
             * @description Approved Auto-Apply is not a value this field can hold (ADR-0016).
             * @enum {string}
             */
            applicationMode: "recommend_only" | "prepare" | "review_submit";
            /** Format: date-time */
            createdAt: string;
        };
        JobSummary: {
            id: string;
            title: string;
            company: string;
            location: string;
            country: string;
            workMode: string;
            jobType: string;
            salaryMin: number | null;
            salaryMax: number | null;
            salaryCurrency: string;
            source: string;
            applyUrl: string;
            /** Format: date-time */
            postedAt: string;
        };
        Match: {
            id: string;
            agentId: string;
            agentName: string;
            score: number;
            /** @enum {string} */
            status: "new" | "reviewed" | "queued" | "applied" | "dismissed" | "ineligible";
            matchedKeywords: string[];
            missingKeywords: string[];
            rationale: string;
            /** Format: date-time */
            matchedAt: string;
        };
        Job: {
            /** @constant */
            object: "job";
            id: string;
            title: string;
            company: string;
            companyLogo: string | null;
            location: string;
            country: string;
            workMode: string;
            jobType: string;
            salaryMin: number | null;
            salaryMax: number | null;
            salaryCurrency: string;
            source: string;
            applyUrl: string;
            applyMethod: string;
            skills: string[];
            requirements: string[];
            nocCode: string | null;
            /** Format: date-time */
            postedAt: string;
            match: components["schemas"]["Match"];
        };
        JobList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["Job"][];
            pagination: components["schemas"]["ListPagination"];
        };
        EligibilityRule: {
            rule: string;
            /** @enum {string} */
            status: "pass" | "fail" | "unknown";
            reason: string;
        };
        JobDetail: {
            /** @constant */
            object: "job";
            id: string;
            title: string;
            company: string;
            companyLogo: string | null;
            location: string;
            country: string;
            workMode: string;
            jobType: string;
            salaryMin: number | null;
            salaryMax: number | null;
            salaryCurrency: string;
            source: string;
            applyUrl: string;
            applyMethod: string;
            skills: string[];
            requirements: string[];
            nocCode: string | null;
            /** Format: date-time */
            postedAt: string;
            match: components["schemas"]["Match"];
            description: string;
            /** @enum {string} */
            activeState: "active" | "unknown" | "closed";
            /** Format: date-time */
            closedAt: string | null;
            eligibility: null | {
                /** @enum {string} */
                outcome: "eligible" | "ineligible" | "unknown";
                /** Format: date-time */
                evaluatedAt: string;
                rules: components["schemas"]["EligibilityRule"][];
            };
            /** @description v1.1: whether the caller saved this posting. */
            saved: boolean;
        };
        MatchDimension: {
            /** @enum {string} */
            dimension: "skills" | "keywords" | "experience" | "seniority" | "location";
            score: number;
            weight: number;
            contribution: number;
            matched: string[];
            missing: string[];
            evidenceIds: string[];
            note: string;
        };
        MatchAnalysis: {
            /** @constant */
            object: "match_analysis";
            id: string;
            jobId: string;
            agentId: string;
            score: number;
            status: string;
            weightVersion: string;
            pipelineVersion: string;
            rationale: string;
            matchedKeywords: string[];
            missingKeywords: string[];
            dimensions: components["schemas"]["MatchDimension"][];
            /** Format: date-time */
            matchedAt: string;
        };
        Application: {
            /** @constant */
            object: "application";
            id: string;
            /** @enum {string} */
            status: "queued" | "applying" | "ready_to_submit" | "submitted" | "failed" | "interviewing" | "offer" | "rejected" | "withdrawn";
            matchScore: number;
            atsScore: number;
            applyChannel: string;
            atsVendor: string | null;
            confirmation: string | null;
            failureReason: string | null;
            keywordsInjected: string[];
            agentId: string | null;
            /** Format: date-time */
            appliedAt: string | null;
            /** Format: date-time */
            respondedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            job: components["schemas"]["JobSummary"];
        };
        ApplicationList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["Application"][];
            pagination: components["schemas"]["ListPagination"];
        };
        Interview: {
            /** @constant */
            object: "interview";
            id: string;
            applicationId: string;
            /** @enum {string} */
            kind: "phone" | "video" | "onsite" | "panel" | "technical" | "other";
            /** Format: date-time */
            scheduledAt: string;
            result: string;
            /** Format: date-time */
            createdAt: string;
            job: null | {
                id: string;
                title: string;
                company: string;
            };
        };
        InterviewList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["Interview"][];
            pagination: components["schemas"]["ListPagination"];
        };
        FolderAnswer: {
            question: string;
            label: string;
            ok: boolean;
            detail: string;
        };
        ApplicationDetail: {
            /** @constant */
            object: "application";
            id: string;
            /** @enum {string} */
            status: "queued" | "applying" | "ready_to_submit" | "submitted" | "failed" | "interviewing" | "offer" | "rejected" | "withdrawn";
            matchScore: number;
            atsScore: number;
            applyChannel: string;
            atsVendor: string | null;
            confirmation: string | null;
            failureReason: string | null;
            keywordsInjected: string[];
            agentId: string | null;
            /** Format: date-time */
            appliedAt: string | null;
            /** Format: date-time */
            respondedAt: string | null;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            job: components["schemas"]["JobSummary"];
            /** @enum {string} */
            outcome: "pending" | "hired" | "rejected" | "withdrawn" | "declined" | "ghosted" | "expired";
            /** Format: date-time */
            outcomeAt: string | null;
            rejectionReason: string | null;
            /** @enum {string} */
            applicationMode: "recommend_only" | "prepare" | "review_submit";
            fieldMappingVersion: string;
            /** @description True only when the employer has authorised a programmatic submission AND the applicant's mode permits it; the POST .../submit is refused otherwise. */
            atsSubmittable: boolean;
            preparedFields: {
                key: string;
                label: string;
                value: string;
                multiline: boolean;
            }[];
            preparedQuestions: {
                id: string;
                question: string;
                /** @enum {string} */
                decision: "fill" | "ask" | "review" | "never";
                /** @enum {string} */
                policy: "AUTO_FILL" | "ASK_IF_CHANGED" | "REQUIRE_REVIEW" | "NEVER_AUTOMATE";
                /** @description Always empty when decision is never. */
                value: string;
            }[];
            history: {
                fromStatus: string;
                toStatus: string;
                actor: string;
                source: string;
                reason: string | null;
                /** Format: date-time */
                at: string;
            }[];
            contacts: {
                id: string;
                role: string;
                name: string;
                organisation: string | null;
            }[];
            interviews: components["schemas"]["Interview"][];
            assessments: {
                id: string;
                kind: string;
                /** Format: date-time */
                dueAt: string | null;
                /** Format: date-time */
                submittedAt: string | null;
                result: string;
            }[];
            followUps: {
                id: string;
                /** Format: date-time */
                dueAt: string;
                /** Format: date-time */
                doneAt: string | null;
                channel: string;
            }[];
            notesCount: number;
            documents: {
                id: string;
                kind: string;
                /** @enum {string} */
                format: "txt" | "pdf" | "docx";
                version: number;
                /** @enum {string} */
                status: "draft" | "submitted";
                contentHash: string;
                sizeBytes: number;
                /** Format: date-time */
                createdAt: string;
            }[];
            communications: {
                threads: number;
                calendarEvents: number;
            };
            completeness: {
                complete: boolean;
                answered: number;
                answers: components["schemas"]["FolderAnswer"][];
            };
        };
        Notification: {
            /** @constant */
            object: "notification";
            id: string;
            /** @enum {string} */
            kind: "activity" | "integration";
            type: string;
            message: string;
            applicationId: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        NotificationList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["Notification"][];
            pagination: components["schemas"]["ListPagination"];
        };
        AnalyticsSummary: {
            /** @constant */
            object: "analytics_summary";
            /** Format: date-time */
            generatedAt: string;
            window: {
                since: string;
                until: string;
                days: number;
            };
            lifetime: {
                applications: number;
                submitted: number;
                interviews: number;
                offers: number;
                responded: number;
            };
            windowed: {
                applications: number;
                submitted: number;
                interviews: number;
                offers: number;
            };
            byStatus: {
                [key: string]: number;
            };
            rates: {
                responseRateParts: number;
                interviewRateParts: number;
                offerRateParts: number;
            };
            scores: {
                averageMatchScore: number;
                averageAtsScore: number;
            };
            agents: {
                total: number;
                active: number;
            };
            matches: {
                total: number;
                new: number;
            };
            quota: null | Record<string, never>;
        };
        AtsRulesetLookup: {
            data: {
                platform: string;
                version: number;
                navigationFlowType: string;
                pacing: string;
                selectorMap: Record<string, never>;
                fallbackSelectors: Record<string, never>;
            };
            meta: {
                cacheBackend: string;
                lookupMs: number;
            };
        };
        ListPagination: {
            limit: number;
            offset: number;
            total: number;
            hasMore: boolean;
        };
        Revoked: {
            /** @constant */
            object: "revoked";
            id: string;
            /** @constant */
            revoked: true;
        };
        DeviceSession: {
            /** @constant */
            object: "device_session";
            id: string;
            name: string;
            /** @enum {string} */
            platform: "ios" | "android" | "web" | "other";
            /** @description The key prefix (jp_live_...), safe to display; never the secret. */
            prefix: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string | null;
            /** Format: date-time */
            expiresAt: string | null;
            /** @description True for the key that made the request. */
            current: boolean;
        };
        DeviceSessionList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["DeviceSession"][];
            pagination: components["schemas"]["ListPagination"];
        };
        DeviceDescriptor: {
            name: string;
            /** @enum {string} */
            platform: "ios" | "android" | "web" | "other";
        };
        /** @description The applicant's own sign-in: password, or a Supabase Auth access token where the deployment has an identity provider (ADR-0004). Mints a device key of kind device with scope write (read + apply:write; never admin), expiring in 90 days, revoked by the owner, by a password change, or by sign-out-everywhere. At most 10 devices; the least recently used is recycled. */
        DeviceSignIn: {
            /** @constant */
            method: "password";
            /** Format: email */
            email: string;
            password: string;
            device: components["schemas"]["DeviceDescriptor"];
        } | {
            /** @constant */
            method: "supabase";
            accessToken: string;
            fullName?: string;
            consents?: ("terms_of_service" | "privacy_policy" | "marketing_email" | "cross_border_ai_processing" | "mailbox_sync" | "calendar_sync")[];
            device: components["schemas"]["DeviceDescriptor"];
        };
        DeviceSessionIssued: {
            /** @constant */
            object: "device_session_issued";
            /** @description The bearer credential, returned exactly once. Keep it in platform secure storage. */
            token: string;
            session: components["schemas"]["DeviceSession"];
            /** @description False until the applicant completed onboarding on the web (profile, consents). */
            onboarded: boolean;
            me: components["schemas"]["Me"];
        };
        MeUpdate: {
            fullName?: string;
            city?: string | null;
            headline?: string | null;
            /**
             * @description approved_auto_apply is refused (ADR-0016).
             * @enum {string}
             */
            applicationMode?: "recommend_only" | "prepare" | "review_submit";
        };
        Consent: {
            /** @constant */
            object: "consent";
            /** @enum {string} */
            purpose: "terms_of_service" | "privacy_policy" | "marketing_email" | "cross_border_ai_processing" | "mailbox_sync" | "calendar_sync";
            /** @description The version a grant records today. */
            version: string;
            /** @description An unrevoked grant of the current version exists. */
            granted: boolean;
            /** Format: date-time */
            grantedAt: string | null;
            grantedVersion: string | null;
            /** @description False while the purpose cannot be recorded (cross-border AI processing waits on L-3). */
            available: boolean;
            /** @description Required to hold an account; withdrawn only by closing it, on the web. */
            required: boolean;
        };
        ConsentList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["Consent"][];
            pagination: components["schemas"]["ListPagination"];
        };
        ConsentUpdate: {
            granted: boolean;
        };
        SavedJobPosting: {
            id: string;
            title: string;
            company: string;
            location: string;
            country: string;
            workMode: string;
            jobType: string;
            salaryMin: number | null;
            salaryMax: number | null;
            salaryCurrency: string;
            source: string;
            applyUrl: string;
            /** Format: date-time */
            postedAt: string;
            /**
             * @description Stage 06: closed only when no source still lists it; unknown is shown as unconfirmed.
             * @enum {string}
             */
            activeState: "active" | "unknown" | "closed";
        };
        SavedJob: {
            /** @constant */
            object: "saved_job";
            jobId: string;
            /** Format: date-time */
            savedAt: string;
            job: components["schemas"]["SavedJobPosting"];
        };
        SavedJobList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["SavedJob"][];
            pagination: components["schemas"]["ListPagination"];
        };
        DocumentLink: {
            /** @constant */
            object: "document_link";
            documentId: string;
            /** @description Absolute; the signature is the authorisation, bound to the owner and the document; ten minutes. */
            url: string;
            /** Format: date-time */
            expiresAt: string;
            format: string;
            kind: string;
            version: number;
        };
        Evidence: {
            /** @constant */
            object: "evidence";
            id: string;
            kind: string;
            sourceType: string;
            /** @description The one sentence the applicant approved; never the structured facts. */
            claim: string;
            /** @enum {string} */
            status: "draft" | "approved" | "superseded" | "revoked";
            version: number;
            /** Format: date-time */
            approvedAt: string | null;
            /** Format: date-time */
            createdAt: string;
        };
        EvidenceList: {
            /** @constant */
            object: "list";
            data: components["schemas"]["Evidence"][];
            pagination: components["schemas"]["ListPagination"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
};
export type $defs = Record<string, never>;
export interface operations {
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MeUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
            /** @description Invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key lacks write, or the mode is unreachable (ADR-0016) */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listRecommendations: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listJobs: {
        parameters: {
            query?: {
                status?: "new" | "reviewed" | "queued" | "applied" | "dismissed";
                agentId?: string;
                minScore?: number;
                country?: "CA" | "US";
                workMode?: "onsite" | "hybrid" | "remote";
                since?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobList"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobDetail"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not among the caller's matches */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getMatchAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                matchId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MatchAnalysis"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not the caller's match */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listApplications: {
        parameters: {
            query?: {
                status?: string;
                agentId?: string;
                since?: string;
                until?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationList"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not the caller's application */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    confirmApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirmed; the folder */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key lacks apply:write */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not the caller's application */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not awaiting confirmation */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    submitApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Submitted; the folder with the confirmation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApplicationDetail"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key lacks apply:write, or the applicant's mode does not permit a submission */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not the caller's application */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not ready, not authorised for this board, already being submitted, or refused by the ATS (the record stays ready for the form) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listInterviews: {
        parameters: {
            query?: {
                from?: string;
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewList"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationList"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAnalyticsSummary: {
        parameters: {
            query?: {
                since?: string;
                until?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsSummary"];
                };
            };
            /** @description since after until */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    getAtsRuleset: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                platform: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AtsRulesetLookup"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Unknown platform or no active ruleset */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listDeviceSessions: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSessionList"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createDeviceSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceSignIn"];
            };
        };
        responses: {
            /** @description Signed in; the key, once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceSessionIssued"];
                };
            };
            /** @description Invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The credential did not verify */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The identity cannot be linked to an account */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Too many sign-in attempts from this address */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No identity provider on this deployment (supabase method only) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeCurrentDeviceSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revoked"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not a device key; revoke it on the web */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    revokeDeviceSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revoked"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key lacks the scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not the caller's device */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listConsents: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentList"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    setConsent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                purpose: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentUpdate"];
            };
        };
        responses: {
            /** @description The purpose after the change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Consent"];
                };
            };
            /** @description Invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key lacks the scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No such purpose */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Required purposes are withdrawn only by closing the account; unavailable purposes cannot be granted */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    saveJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJob"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key lacks the scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not a posting the caller's agents matched */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    unsaveJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Unsaved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Revoked"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description The key lacks the scope */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not a posting the caller's agents matched */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listSavedJobs: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SavedJobList"];
                };
            };
            /** @description Invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    createDocumentLink: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                applicationId: string;
                documentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description The link */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DocumentLink"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Not the caller's document */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listEvidence: {
        parameters: {
            query?: {
                limit?: number;
                offset?: number;
                /** @description Default: draft and approved. */
                status?: "draft" | "approved" | "superseded" | "revoked";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvidenceList"];
                };
            };
            /** @description Invalid parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No or invalid key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Rate limit exceeded for this key */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
