-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903110100_rls_connector_tables). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- AtsRuleset (system)
ALTER TABLE "AtsRuleset" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AtsRuleset" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "AtsRuleset";
DROP POLICY IF EXISTS tenant_access ON "AtsRuleset";
DROP POLICY IF EXISTS tenant_read ON "AtsRuleset";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "AtsRuleset" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "AtsRuleset";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- JobSnapshot (reference)
ALTER TABLE "JobSnapshot" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobSnapshot" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "JobSnapshot";
DROP POLICY IF EXISTS tenant_access ON "JobSnapshot";
DROP POLICY IF EXISTS tenant_read ON "JobSnapshot";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "JobSnapshot" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "JobSnapshot";
CREATE POLICY tenant_read ON "JobSnapshot" FOR SELECT TO app_tenant USING (true);

-- JobSource (system)
ALTER TABLE "JobSource" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobSource" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "JobSource";
DROP POLICY IF EXISTS tenant_access ON "JobSource";
DROP POLICY IF EXISTS tenant_read ON "JobSource";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "JobSource" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "JobSource";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- JobSourceRun (system)
ALTER TABLE "JobSourceRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobSourceRun" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "JobSourceRun";
DROP POLICY IF EXISTS tenant_access ON "JobSourceRun";
DROP POLICY IF EXISTS tenant_read ON "JobSourceRun";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "JobSourceRun" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "JobSourceRun";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)
