-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903090100_rls_evidence_tables). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- AiRun (reference)
ALTER TABLE "AiRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AiRun" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "AiRun";
DROP POLICY IF EXISTS tenant_access ON "AiRun";
DROP POLICY IF EXISTS tenant_read ON "AiRun";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "AiRun" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "AiRun";
CREATE POLICY tenant_read ON "AiRun" FOR SELECT TO app_tenant USING ("userId" = app_current_user_id());

-- ApplicationQuestion (user)
ALTER TABLE "ApplicationQuestion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApplicationQuestion" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApplicationQuestion";
DROP POLICY IF EXISTS tenant_access ON "ApplicationQuestion";
DROP POLICY IF EXISTS tenant_read ON "ApplicationQuestion";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApplicationQuestion" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApplicationQuestion";
CREATE POLICY tenant_access ON "ApplicationQuestion" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CareerEvidence (user)
ALTER TABLE "CareerEvidence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CareerEvidence" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CareerEvidence";
DROP POLICY IF EXISTS tenant_access ON "CareerEvidence";
DROP POLICY IF EXISTS tenant_read ON "CareerEvidence";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CareerEvidence" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CareerEvidence";
CREATE POLICY tenant_access ON "CareerEvidence" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- PromptVersion (system)
ALTER TABLE "PromptVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PromptVersion" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "PromptVersion";
DROP POLICY IF EXISTS tenant_access ON "PromptVersion";
DROP POLICY IF EXISTS tenant_read ON "PromptVersion";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "PromptVersion" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "PromptVersion";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)
