-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260905160100_rls_case_management). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- Case (custom)
ALTER TABLE "Case" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Case" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Case";
DROP POLICY IF EXISTS tenant_access ON "Case";
DROP POLICY IF EXISTS tenant_read ON "Case";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Case" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Case";
CREATE POLICY tenant_access ON "Case" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));
CREATE POLICY tenant_read ON "Case" FOR SELECT TO app_tenant USING (("organizationId" = ANY (app_member_organization_ids()) OR "clientUserId" = app_current_user_id()));

-- CaseAssessment (org)
ALTER TABLE "CaseAssessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseAssessment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CaseAssessment";
DROP POLICY IF EXISTS tenant_access ON "CaseAssessment";
DROP POLICY IF EXISTS tenant_read ON "CaseAssessment";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CaseAssessment" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CaseAssessment";
CREATE POLICY tenant_access ON "CaseAssessment" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- CaseFollowUp (org)
ALTER TABLE "CaseFollowUp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseFollowUp" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CaseFollowUp";
DROP POLICY IF EXISTS tenant_access ON "CaseFollowUp";
DROP POLICY IF EXISTS tenant_read ON "CaseFollowUp";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CaseFollowUp" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CaseFollowUp";
CREATE POLICY tenant_access ON "CaseFollowUp" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- CaseNote (org)
ALTER TABLE "CaseNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseNote" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CaseNote";
DROP POLICY IF EXISTS tenant_access ON "CaseNote";
DROP POLICY IF EXISTS tenant_read ON "CaseNote";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CaseNote" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CaseNote";
CREATE POLICY tenant_access ON "CaseNote" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- CaseOutcome (org)
ALTER TABLE "CaseOutcome" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseOutcome" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CaseOutcome";
DROP POLICY IF EXISTS tenant_access ON "CaseOutcome";
DROP POLICY IF EXISTS tenant_read ON "CaseOutcome";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CaseOutcome" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CaseOutcome";
CREATE POLICY tenant_access ON "CaseOutcome" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- CaseRecommendation (org)
ALTER TABLE "CaseRecommendation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseRecommendation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CaseRecommendation";
DROP POLICY IF EXISTS tenant_access ON "CaseRecommendation";
DROP POLICY IF EXISTS tenant_read ON "CaseRecommendation";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CaseRecommendation" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CaseRecommendation";
CREATE POLICY tenant_access ON "CaseRecommendation" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- CaseTask (org)
ALTER TABLE "CaseTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CaseTask" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CaseTask";
DROP POLICY IF EXISTS tenant_access ON "CaseTask";
DROP POLICY IF EXISTS tenant_read ON "CaseTask";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CaseTask" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CaseTask";
CREATE POLICY tenant_access ON "CaseTask" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- RetentionPolicy (orgReadOnly)
ALTER TABLE "RetentionPolicy" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RetentionPolicy" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "RetentionPolicy";
DROP POLICY IF EXISTS tenant_access ON "RetentionPolicy";
DROP POLICY IF EXISTS tenant_read ON "RetentionPolicy";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "RetentionPolicy" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "RetentionPolicy";
CREATE POLICY tenant_read ON "RetentionPolicy" FOR SELECT TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids()));
