-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903081400_rls_candidate_tables). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- Achievement (user)
ALTER TABLE "Achievement" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Achievement" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Achievement";
DROP POLICY IF EXISTS tenant_access ON "Achievement";
DROP POLICY IF EXISTS tenant_read ON "Achievement";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Achievement" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Achievement";
CREATE POLICY tenant_access ON "Achievement" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CandidateLanguage (user)
ALTER TABLE "CandidateLanguage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CandidateLanguage" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CandidateLanguage";
DROP POLICY IF EXISTS tenant_access ON "CandidateLanguage";
DROP POLICY IF EXISTS tenant_read ON "CandidateLanguage";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CandidateLanguage" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CandidateLanguage";
CREATE POLICY tenant_access ON "CandidateLanguage" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CandidateProfile (user)
ALTER TABLE "CandidateProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CandidateProfile" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CandidateProfile";
DROP POLICY IF EXISTS tenant_access ON "CandidateProfile";
DROP POLICY IF EXISTS tenant_read ON "CandidateProfile";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CandidateProfile" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CandidateProfile";
CREATE POLICY tenant_access ON "CandidateProfile" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CandidateSkill (user)
ALTER TABLE "CandidateSkill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CandidateSkill" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CandidateSkill";
DROP POLICY IF EXISTS tenant_access ON "CandidateSkill";
DROP POLICY IF EXISTS tenant_read ON "CandidateSkill";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CandidateSkill" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CandidateSkill";
CREATE POLICY tenant_access ON "CandidateSkill" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CareerPreferences (user)
ALTER TABLE "CareerPreferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CareerPreferences" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CareerPreferences";
DROP POLICY IF EXISTS tenant_access ON "CareerPreferences";
DROP POLICY IF EXISTS tenant_read ON "CareerPreferences";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CareerPreferences" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CareerPreferences";
CREATE POLICY tenant_access ON "CareerPreferences" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Certification (user)
ALTER TABLE "Certification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Certification" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Certification";
DROP POLICY IF EXISTS tenant_access ON "Certification";
DROP POLICY IF EXISTS tenant_read ON "Certification";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Certification" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Certification";
CREATE POLICY tenant_access ON "Certification" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Education (user)
ALTER TABLE "Education" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Education" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Education";
DROP POLICY IF EXISTS tenant_access ON "Education";
DROP POLICY IF EXISTS tenant_read ON "Education";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Education" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Education";
CREATE POLICY tenant_access ON "Education" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- EmploymentHistory (user)
ALTER TABLE "EmploymentHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmploymentHistory" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmploymentHistory";
DROP POLICY IF EXISTS tenant_access ON "EmploymentHistory";
DROP POLICY IF EXISTS tenant_read ON "EmploymentHistory";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmploymentHistory" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmploymentHistory";
CREATE POLICY tenant_access ON "EmploymentHistory" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Project (user)
ALTER TABLE "Project" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Project" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Project";
DROP POLICY IF EXISTS tenant_access ON "Project";
DROP POLICY IF EXISTS tenant_read ON "Project";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Project" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Project";
CREATE POLICY tenant_access ON "Project" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Skill (reference)
ALTER TABLE "Skill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Skill" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Skill";
DROP POLICY IF EXISTS tenant_access ON "Skill";
DROP POLICY IF EXISTS tenant_read ON "Skill";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Skill" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Skill";
CREATE POLICY tenant_read ON "Skill" FOR SELECT TO app_tenant USING (true);

-- WorkAuthorization (user)
ALTER TABLE "WorkAuthorization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WorkAuthorization" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "WorkAuthorization";
DROP POLICY IF EXISTS tenant_access ON "WorkAuthorization";
DROP POLICY IF EXISTS tenant_read ON "WorkAuthorization";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "WorkAuthorization" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "WorkAuthorization";
CREATE POLICY tenant_access ON "WorkAuthorization" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());
