-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903073000_row_level_security). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 1. The tenant role. NOLOGIN: it is reached only by SET LOCAL ROLE inside a
--    transaction that has already established tenant context. NOINHERIT so
--    it never picks up the migration role's privileges by membership.
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'app_tenant') THEN
    CREATE ROLE app_tenant NOLOGIN NOINHERIT NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;
  END IF;
  -- The connection role must be a member of the tenant role to SET ROLE to it.
  EXECUTE format('GRANT app_tenant TO %I', current_user);
END $$;

GRANT USAGE ON SCHEMA public TO app_tenant;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO app_tenant;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO app_tenant;
-- Prisma's migration ledger is not application data and is not classified;
-- the blanket grant above must not reach it. Conditional because Prisma's
-- SHADOW database (used by `migrate dev` to compute diffs) replays the
-- migration files without creating the ledger table.
DO $$ BEGIN
  IF to_regclass('public._prisma_migrations') IS NOT NULL THEN
    EXECUTE 'REVOKE ALL ON "_prisma_migrations" FROM app_tenant';
  END IF;
END $$;
-- Tables created by later migrations get the same grants; their policies are
-- still their own migration's job, and the coverage test fails until they exist.
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_tenant;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO app_tenant;

-- ---------------------------------------------------------------------------
-- 2. Context accessors. STABLE so the planner evaluates them once per
--    statement. current_setting(name, TRUE) never raises; NULLIF folds the
--    empty string a recycled connection reports into NULL, and NULL is equal
--    to nothing, so both "never set" and "set and cleared" match no row.
-- ---------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION app_current_user_id() RETURNS text
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $$ SELECT NULLIF(current_setting('app.current_user_id', TRUE), '') $$;

CREATE OR REPLACE FUNCTION app_current_organization_id() RETURNS text
  LANGUAGE sql STABLE PARALLEL SAFE
  AS $$ SELECT NULLIF(current_setting('app.current_organization_id', TRUE), '') $$;

-- The organisations the current user is an ACCEPTED, not-removed member of.
-- SECURITY DEFINER so the Membership read inside it is not itself subject to
-- the Membership policy, which would otherwise recurse (PostgreSQL refuses a
-- policy that references its own table). Owned by the migration role, whose
-- unconditional policy below is what the definer context relies on.
CREATE OR REPLACE FUNCTION app_member_organization_ids() RETURNS text[]
  LANGUAGE sql STABLE SECURITY DEFINER
  SET search_path = public
  AS $$
    SELECT COALESCE(array_agg(m."organizationId"), ARRAY[]::text[])
      FROM "Membership" m
     WHERE m."userId" = NULLIF(current_setting('app.current_user_id', TRUE), '')
       AND m."acceptedAt" IS NOT NULL
       AND m."removedAt" IS NULL
  $$;

REVOKE ALL ON FUNCTION app_current_user_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION app_current_organization_id() FROM PUBLIC;
REVOKE ALL ON FUNCTION app_member_organization_ids() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION app_current_user_id() TO app_tenant;
GRANT EXECUTE ON FUNCTION app_current_organization_id() TO app_tenant;
GRANT EXECUTE ON FUNCTION app_member_organization_ids() TO app_tenant;

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- ActivityEvent (user)
ALTER TABLE "ActivityEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ActivityEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ActivityEvent";
DROP POLICY IF EXISTS tenant_access ON "ActivityEvent";
DROP POLICY IF EXISTS tenant_read ON "ActivityEvent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ActivityEvent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ActivityEvent";
CREATE POLICY tenant_access ON "ActivityEvent" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Agent (user)
ALTER TABLE "Agent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Agent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Agent";
DROP POLICY IF EXISTS tenant_access ON "Agent";
DROP POLICY IF EXISTS tenant_read ON "Agent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Agent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Agent";
CREATE POLICY tenant_access ON "Agent" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- AgentSchedule (viaParent)
ALTER TABLE "AgentSchedule" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgentSchedule" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "AgentSchedule";
DROP POLICY IF EXISTS tenant_access ON "AgentSchedule";
DROP POLICY IF EXISTS tenant_read ON "AgentSchedule";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "AgentSchedule" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "AgentSchedule";
CREATE POLICY tenant_access ON "AgentSchedule" TO app_tenant USING (EXISTS (SELECT 1 FROM "Agent" p WHERE p."id" = "AgentSchedule"."agentId")) WITH CHECK (EXISTS (SELECT 1 FROM "Agent" p WHERE p."id" = "AgentSchedule"."agentId"));

-- ApiIdempotencyRecord (user)
ALTER TABLE "ApiIdempotencyRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiIdempotencyRecord" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApiIdempotencyRecord";
DROP POLICY IF EXISTS tenant_access ON "ApiIdempotencyRecord";
DROP POLICY IF EXISTS tenant_read ON "ApiIdempotencyRecord";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApiIdempotencyRecord" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApiIdempotencyRecord";
CREATE POLICY tenant_access ON "ApiIdempotencyRecord" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ApiKey (userOrOrg)
ALTER TABLE "ApiKey" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApiKey" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApiKey";
DROP POLICY IF EXISTS tenant_access ON "ApiKey";
DROP POLICY IF EXISTS tenant_read ON "ApiKey";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApiKey" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApiKey";
CREATE POLICY tenant_access ON "ApiKey" TO app_tenant USING (("userId" = app_current_user_id() OR "organizationId" = ANY (app_member_organization_ids()))) WITH CHECK (("userId" = app_current_user_id() OR "organizationId" = ANY (app_member_organization_ids())));

-- Application (user)
ALTER TABLE "Application" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Application" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Application";
DROP POLICY IF EXISTS tenant_access ON "Application";
DROP POLICY IF EXISTS tenant_read ON "Application";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Application" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Application";
CREATE POLICY tenant_access ON "Application" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- AuditLog (system)
ALTER TABLE "AuditLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AuditLog" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "AuditLog";
DROP POLICY IF EXISTS tenant_access ON "AuditLog";
DROP POLICY IF EXISTS tenant_read ON "AuditLog";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "AuditLog" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "AuditLog";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- BillingProfile (user)
ALTER TABLE "BillingProfile" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BillingProfile" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "BillingProfile";
DROP POLICY IF EXISTS tenant_access ON "BillingProfile";
DROP POLICY IF EXISTS tenant_read ON "BillingProfile";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "BillingProfile" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "BillingProfile";
CREATE POLICY tenant_access ON "BillingProfile" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ConsentRecord (user)
ALTER TABLE "ConsentRecord" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ConsentRecord" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ConsentRecord";
DROP POLICY IF EXISTS tenant_access ON "ConsentRecord";
DROP POLICY IF EXISTS tenant_read ON "ConsentRecord";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ConsentRecord" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ConsentRecord";
CREATE POLICY tenant_access ON "ConsentRecord" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Coupon (system)
ALTER TABLE "Coupon" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Coupon" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Coupon";
DROP POLICY IF EXISTS tenant_access ON "Coupon";
DROP POLICY IF EXISTS tenant_read ON "Coupon";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Coupon" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Coupon";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- CouponRedemption (user)
ALTER TABLE "CouponRedemption" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CouponRedemption" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CouponRedemption";
DROP POLICY IF EXISTS tenant_access ON "CouponRedemption";
DROP POLICY IF EXISTS tenant_read ON "CouponRedemption";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CouponRedemption" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CouponRedemption";
CREATE POLICY tenant_access ON "CouponRedemption" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CreditLedgerEntry (user)
ALTER TABLE "CreditLedgerEntry" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditLedgerEntry" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CreditLedgerEntry";
DROP POLICY IF EXISTS tenant_access ON "CreditLedgerEntry";
DROP POLICY IF EXISTS tenant_read ON "CreditLedgerEntry";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CreditLedgerEntry" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CreditLedgerEntry";
CREATE POLICY tenant_access ON "CreditLedgerEntry" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CreditNote (user)
ALTER TABLE "CreditNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditNote" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CreditNote";
DROP POLICY IF EXISTS tenant_access ON "CreditNote";
DROP POLICY IF EXISTS tenant_read ON "CreditNote";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CreditNote" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CreditNote";
CREATE POLICY tenant_access ON "CreditNote" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CreditNoteLine (viaParent)
ALTER TABLE "CreditNoteLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CreditNoteLine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CreditNoteLine";
DROP POLICY IF EXISTS tenant_access ON "CreditNoteLine";
DROP POLICY IF EXISTS tenant_read ON "CreditNoteLine";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CreditNoteLine" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CreditNoteLine";
CREATE POLICY tenant_access ON "CreditNoteLine" TO app_tenant USING (EXISTS (SELECT 1 FROM "CreditNote" p WHERE p."id" = "CreditNoteLine"."creditNoteId")) WITH CHECK (EXISTS (SELECT 1 FROM "CreditNote" p WHERE p."id" = "CreditNoteLine"."creditNoteId"));

-- CrmActivity (system)
ALTER TABLE "CrmActivity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CrmActivity" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CrmActivity";
DROP POLICY IF EXISTS tenant_access ON "CrmActivity";
DROP POLICY IF EXISTS tenant_read ON "CrmActivity";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CrmActivity" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CrmActivity";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- CrmNote (system)
ALTER TABLE "CrmNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CrmNote" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CrmNote";
DROP POLICY IF EXISTS tenant_access ON "CrmNote";
DROP POLICY IF EXISTS tenant_read ON "CrmNote";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CrmNote" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CrmNote";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- CrmTask (system)
ALTER TABLE "CrmTask" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CrmTask" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CrmTask";
DROP POLICY IF EXISTS tenant_access ON "CrmTask";
DROP POLICY IF EXISTS tenant_read ON "CrmTask";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CrmTask" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CrmTask";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- Customer (system)
ALTER TABLE "Customer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Customer" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Customer";
DROP POLICY IF EXISTS tenant_access ON "Customer";
DROP POLICY IF EXISTS tenant_read ON "Customer";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Customer" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Customer";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- DailyMetric (system)
ALTER TABLE "DailyMetric" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyMetric" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "DailyMetric";
DROP POLICY IF EXISTS tenant_access ON "DailyMetric";
DROP POLICY IF EXISTS tenant_read ON "DailyMetric";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "DailyMetric" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "DailyMetric";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- DailyRevenueRollup (system)
ALTER TABLE "DailyRevenueRollup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyRevenueRollup" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "DailyRevenueRollup";
DROP POLICY IF EXISTS tenant_access ON "DailyRevenueRollup";
DROP POLICY IF EXISTS tenant_read ON "DailyRevenueRollup";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "DailyRevenueRollup" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "DailyRevenueRollup";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- DailyUsageRollup (user)
ALTER TABLE "DailyUsageRollup" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DailyUsageRollup" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "DailyUsageRollup";
DROP POLICY IF EXISTS tenant_access ON "DailyUsageRollup";
DROP POLICY IF EXISTS tenant_read ON "DailyUsageRollup";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "DailyUsageRollup" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "DailyUsageRollup";
CREATE POLICY tenant_access ON "DailyUsageRollup" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- DeletionRequest (user)
ALTER TABLE "DeletionRequest" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DeletionRequest" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "DeletionRequest";
DROP POLICY IF EXISTS tenant_access ON "DeletionRequest";
DROP POLICY IF EXISTS tenant_read ON "DeletionRequest";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "DeletionRequest" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "DeletionRequest";
CREATE POLICY tenant_access ON "DeletionRequest" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- DocumentSequence (system)
ALTER TABLE "DocumentSequence" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DocumentSequence" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "DocumentSequence";
DROP POLICY IF EXISTS tenant_access ON "DocumentSequence";
DROP POLICY IF EXISTS tenant_read ON "DocumentSequence";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "DocumentSequence" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "DocumentSequence";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- DunningAttempt (viaParent)
ALTER TABLE "DunningAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DunningAttempt" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "DunningAttempt";
DROP POLICY IF EXISTS tenant_access ON "DunningAttempt";
DROP POLICY IF EXISTS tenant_read ON "DunningAttempt";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "DunningAttempt" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "DunningAttempt";
CREATE POLICY tenant_access ON "DunningAttempt" TO app_tenant USING (EXISTS (SELECT 1 FROM "Invoice" p WHERE p."id" = "DunningAttempt"."invoiceId")) WITH CHECK (EXISTS (SELECT 1 FROM "Invoice" p WHERE p."id" = "DunningAttempt"."invoiceId"));

-- DunningState (user)
ALTER TABLE "DunningState" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DunningState" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "DunningState";
DROP POLICY IF EXISTS tenant_access ON "DunningState";
DROP POLICY IF EXISTS tenant_read ON "DunningState";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "DunningState" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "DunningState";
CREATE POLICY tenant_access ON "DunningState" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- EmailLog (user)
ALTER TABLE "EmailLog" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailLog" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmailLog";
DROP POLICY IF EXISTS tenant_access ON "EmailLog";
DROP POLICY IF EXISTS tenant_read ON "EmailLog";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmailLog" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmailLog";
CREATE POLICY tenant_access ON "EmailLog" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- EmailSuppression (system)
ALTER TABLE "EmailSuppression" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailSuppression" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmailSuppression";
DROP POLICY IF EXISTS tenant_access ON "EmailSuppression";
DROP POLICY IF EXISTS tenant_read ON "EmailSuppression";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmailSuppression" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmailSuppression";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- EmailToken (user)
ALTER TABLE "EmailToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailToken" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmailToken";
DROP POLICY IF EXISTS tenant_access ON "EmailToken";
DROP POLICY IF EXISTS tenant_read ON "EmailToken";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmailToken" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmailToken";
CREATE POLICY tenant_access ON "EmailToken" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ExperimentAssignment (user)
ALTER TABLE "ExperimentAssignment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExperimentAssignment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ExperimentAssignment";
DROP POLICY IF EXISTS tenant_access ON "ExperimentAssignment";
DROP POLICY IF EXISTS tenant_read ON "ExperimentAssignment";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ExperimentAssignment" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ExperimentAssignment";
CREATE POLICY tenant_access ON "ExperimentAssignment" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ExportJob (user)
ALTER TABLE "ExportJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ExportJob" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ExportJob";
DROP POLICY IF EXISTS tenant_access ON "ExportJob";
DROP POLICY IF EXISTS tenant_read ON "ExportJob";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ExportJob" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ExportJob";
CREATE POLICY tenant_access ON "ExportJob" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- FeatureFlag (reference)
ALTER TABLE "FeatureFlag" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "FeatureFlag" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "FeatureFlag";
DROP POLICY IF EXISTS tenant_access ON "FeatureFlag";
DROP POLICY IF EXISTS tenant_read ON "FeatureFlag";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "FeatureFlag" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "FeatureFlag";
CREATE POLICY tenant_read ON "FeatureFlag" FOR SELECT TO app_tenant USING (true);

-- ImpersonationSession (system)
ALTER TABLE "ImpersonationSession" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ImpersonationSession" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ImpersonationSession";
DROP POLICY IF EXISTS tenant_access ON "ImpersonationSession";
DROP POLICY IF EXISTS tenant_read ON "ImpersonationSession";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ImpersonationSession" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ImpersonationSession";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- Integration (user)
ALTER TABLE "Integration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Integration" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Integration";
DROP POLICY IF EXISTS tenant_access ON "Integration";
DROP POLICY IF EXISTS tenant_read ON "Integration";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Integration" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Integration";
CREATE POLICY tenant_access ON "Integration" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- InterviewPrep (user)
ALTER TABLE "InterviewPrep" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InterviewPrep" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "InterviewPrep";
DROP POLICY IF EXISTS tenant_access ON "InterviewPrep";
DROP POLICY IF EXISTS tenant_read ON "InterviewPrep";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "InterviewPrep" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "InterviewPrep";
CREATE POLICY tenant_access ON "InterviewPrep" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Invoice (userOrOrg)
ALTER TABLE "Invoice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Invoice" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Invoice";
DROP POLICY IF EXISTS tenant_access ON "Invoice";
DROP POLICY IF EXISTS tenant_read ON "Invoice";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Invoice" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Invoice";
CREATE POLICY tenant_access ON "Invoice" TO app_tenant USING (("userId" = app_current_user_id() OR "organizationId" = ANY (app_member_organization_ids()))) WITH CHECK (("userId" = app_current_user_id() OR "organizationId" = ANY (app_member_organization_ids())));

-- InvoiceLine (viaParent)
ALTER TABLE "InvoiceLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceLine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "InvoiceLine";
DROP POLICY IF EXISTS tenant_access ON "InvoiceLine";
DROP POLICY IF EXISTS tenant_read ON "InvoiceLine";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "InvoiceLine" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "InvoiceLine";
CREATE POLICY tenant_access ON "InvoiceLine" TO app_tenant USING (EXISTS (SELECT 1 FROM "Invoice" p WHERE p."id" = "InvoiceLine"."invoiceId")) WITH CHECK (EXISTS (SELECT 1 FROM "Invoice" p WHERE p."id" = "InvoiceLine"."invoiceId"));

-- InvoiceTaxLine (viaParent)
ALTER TABLE "InvoiceTaxLine" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "InvoiceTaxLine" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "InvoiceTaxLine";
DROP POLICY IF EXISTS tenant_access ON "InvoiceTaxLine";
DROP POLICY IF EXISTS tenant_read ON "InvoiceTaxLine";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "InvoiceTaxLine" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "InvoiceTaxLine";
CREATE POLICY tenant_access ON "InvoiceTaxLine" TO app_tenant USING (EXISTS (SELECT 1 FROM "Invoice" p WHERE p."id" = "InvoiceTaxLine"."invoiceId")) WITH CHECK (EXISTS (SELECT 1 FROM "Invoice" p WHERE p."id" = "InvoiceTaxLine"."invoiceId"));

-- Job (reference)
ALTER TABLE "Job" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Job" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Job";
DROP POLICY IF EXISTS tenant_access ON "Job";
DROP POLICY IF EXISTS tenant_read ON "Job";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Job" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Job";
CREATE POLICY tenant_read ON "Job" FOR SELECT TO app_tenant USING (true);

-- JobMatch (viaParent)
ALTER TABLE "JobMatch" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobMatch" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "JobMatch";
DROP POLICY IF EXISTS tenant_access ON "JobMatch";
DROP POLICY IF EXISTS tenant_read ON "JobMatch";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "JobMatch" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "JobMatch";
CREATE POLICY tenant_access ON "JobMatch" TO app_tenant USING (EXISTS (SELECT 1 FROM "Agent" p WHERE p."id" = "JobMatch"."agentId")) WITH CHECK (EXISTS (SELECT 1 FROM "Agent" p WHERE p."id" = "JobMatch"."agentId"));

-- Membership (orgReadOnly)
ALTER TABLE "Membership" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Membership" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Membership";
DROP POLICY IF EXISTS tenant_access ON "Membership";
DROP POLICY IF EXISTS tenant_read ON "Membership";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Membership" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Membership";
CREATE POLICY tenant_read ON "Membership" FOR SELECT TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids()));

-- Notification (user)
ALTER TABLE "Notification" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Notification" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Notification";
DROP POLICY IF EXISTS tenant_access ON "Notification";
DROP POLICY IF EXISTS tenant_read ON "Notification";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Notification" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Notification";
CREATE POLICY tenant_access ON "Notification" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- NotificationPreference (user)
ALTER TABLE "NotificationPreference" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NotificationPreference" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "NotificationPreference";
DROP POLICY IF EXISTS tenant_access ON "NotificationPreference";
DROP POLICY IF EXISTS tenant_read ON "NotificationPreference";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "NotificationPreference" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "NotificationPreference";
CREATE POLICY tenant_access ON "NotificationPreference" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Organization (orgReadOnly)
ALTER TABLE "Organization" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Organization" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Organization";
DROP POLICY IF EXISTS tenant_access ON "Organization";
DROP POLICY IF EXISTS tenant_read ON "Organization";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Organization" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Organization";
CREATE POLICY tenant_read ON "Organization" FOR SELECT TO app_tenant USING ("id" = ANY (app_member_organization_ids()));

-- OutboundEvent (user)
ALTER TABLE "OutboundEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OutboundEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "OutboundEvent";
DROP POLICY IF EXISTS tenant_access ON "OutboundEvent";
DROP POLICY IF EXISTS tenant_read ON "OutboundEvent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "OutboundEvent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "OutboundEvent";
CREATE POLICY tenant_access ON "OutboundEvent" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Payment (user)
ALTER TABLE "Payment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Payment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Payment";
DROP POLICY IF EXISTS tenant_access ON "Payment";
DROP POLICY IF EXISTS tenant_read ON "Payment";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Payment" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Payment";
CREATE POLICY tenant_access ON "Payment" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- PaymentAllocation (viaParent)
ALTER TABLE "PaymentAllocation" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentAllocation" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "PaymentAllocation";
DROP POLICY IF EXISTS tenant_access ON "PaymentAllocation";
DROP POLICY IF EXISTS tenant_read ON "PaymentAllocation";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "PaymentAllocation" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "PaymentAllocation";
CREATE POLICY tenant_access ON "PaymentAllocation" TO app_tenant USING (EXISTS (SELECT 1 FROM "Payment" p WHERE p."id" = "PaymentAllocation"."paymentId")) WITH CHECK (EXISTS (SELECT 1 FROM "Payment" p WHERE p."id" = "PaymentAllocation"."paymentId"));

-- PaymentAttempt (viaParent)
ALTER TABLE "PaymentAttempt" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentAttempt" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "PaymentAttempt";
DROP POLICY IF EXISTS tenant_access ON "PaymentAttempt";
DROP POLICY IF EXISTS tenant_read ON "PaymentAttempt";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "PaymentAttempt" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "PaymentAttempt";
CREATE POLICY tenant_access ON "PaymentAttempt" TO app_tenant USING (EXISTS (SELECT 1 FROM "Payment" p WHERE p."id" = "PaymentAttempt"."paymentId")) WITH CHECK (EXISTS (SELECT 1 FROM "Payment" p WHERE p."id" = "PaymentAttempt"."paymentId"));

-- PaymentMethod (user)
ALTER TABLE "PaymentMethod" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PaymentMethod" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "PaymentMethod";
DROP POLICY IF EXISTS tenant_access ON "PaymentMethod";
DROP POLICY IF EXISTS tenant_read ON "PaymentMethod";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "PaymentMethod" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "PaymentMethod";
CREATE POLICY tenant_access ON "PaymentMethod" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Plan (reference)
ALTER TABLE "Plan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Plan" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Plan";
DROP POLICY IF EXISTS tenant_access ON "Plan";
DROP POLICY IF EXISTS tenant_read ON "Plan";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Plan" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Plan";
CREATE POLICY tenant_read ON "Plan" FOR SELECT TO app_tenant USING (true);

-- PlanPrice (reference)
ALTER TABLE "PlanPrice" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PlanPrice" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "PlanPrice";
DROP POLICY IF EXISTS tenant_access ON "PlanPrice";
DROP POLICY IF EXISTS tenant_read ON "PlanPrice";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "PlanPrice" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "PlanPrice";
CREATE POLICY tenant_read ON "PlanPrice" FOR SELECT TO app_tenant USING ("active" = true);

-- Referral (custom)
ALTER TABLE "Referral" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Referral" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Referral";
DROP POLICY IF EXISTS tenant_access ON "Referral";
DROP POLICY IF EXISTS tenant_read ON "Referral";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Referral" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Referral";
CREATE POLICY tenant_access ON "Referral" TO app_tenant USING (("referrerUserId" = app_current_user_id() OR "refereeUserId" = app_current_user_id())) WITH CHECK (("referrerUserId" = app_current_user_id() OR "refereeUserId" = app_current_user_id()));

-- ReferralCode (user)
ALTER TABLE "ReferralCode" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ReferralCode" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ReferralCode";
DROP POLICY IF EXISTS tenant_access ON "ReferralCode";
DROP POLICY IF EXISTS tenant_read ON "ReferralCode";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ReferralCode" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ReferralCode";
CREATE POLICY tenant_access ON "ReferralCode" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Refund (user)
ALTER TABLE "Refund" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Refund" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Refund";
DROP POLICY IF EXISTS tenant_access ON "Refund";
DROP POLICY IF EXISTS tenant_read ON "Refund";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Refund" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Refund";
CREATE POLICY tenant_access ON "Refund" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Resume (user)
ALTER TABLE "Resume" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Resume" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Resume";
DROP POLICY IF EXISTS tenant_access ON "Resume";
DROP POLICY IF EXISTS tenant_read ON "Resume";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Resume" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Resume";
CREATE POLICY tenant_access ON "Resume" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ResumeScan (user)
ALTER TABLE "ResumeScan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ResumeScan" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ResumeScan";
DROP POLICY IF EXISTS tenant_access ON "ResumeScan";
DROP POLICY IF EXISTS tenant_read ON "ResumeScan";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ResumeScan" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ResumeScan";
CREATE POLICY tenant_access ON "ResumeScan" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- RollupRun (system)
ALTER TABLE "RollupRun" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "RollupRun" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "RollupRun";
DROP POLICY IF EXISTS tenant_access ON "RollupRun";
DROP POLICY IF EXISTS tenant_read ON "RollupRun";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "RollupRun" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "RollupRun";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- SavedJob (user)
ALTER TABLE "SavedJob" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SavedJob" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SavedJob";
DROP POLICY IF EXISTS tenant_access ON "SavedJob";
DROP POLICY IF EXISTS tenant_read ON "SavedJob";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SavedJob" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SavedJob";
CREATE POLICY tenant_access ON "SavedJob" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Session (user)
ALTER TABLE "Session" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Session" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Session";
DROP POLICY IF EXISTS tenant_access ON "Session";
DROP POLICY IF EXISTS tenant_read ON "Session";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Session" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Session";
CREATE POLICY tenant_access ON "Session" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Subscription (user)
ALTER TABLE "Subscription" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Subscription" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Subscription";
DROP POLICY IF EXISTS tenant_access ON "Subscription";
DROP POLICY IF EXISTS tenant_read ON "Subscription";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Subscription" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Subscription";
CREATE POLICY tenant_access ON "Subscription" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- SubscriptionEvent (user)
ALTER TABLE "SubscriptionEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SubscriptionEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SubscriptionEvent";
DROP POLICY IF EXISTS tenant_access ON "SubscriptionEvent";
DROP POLICY IF EXISTS tenant_read ON "SubscriptionEvent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SubscriptionEvent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SubscriptionEvent";
CREATE POLICY tenant_access ON "SubscriptionEvent" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- SupportMessage (viaParent)
ALTER TABLE "SupportMessage" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupportMessage" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SupportMessage";
DROP POLICY IF EXISTS tenant_access ON "SupportMessage";
DROP POLICY IF EXISTS tenant_read ON "SupportMessage";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SupportMessage" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SupportMessage";
CREATE POLICY tenant_access ON "SupportMessage" TO app_tenant USING ((EXISTS (SELECT 1 FROM "SupportTicket" p WHERE p."id" = "SupportMessage"."ticketId") AND "internal" = false)) WITH CHECK ((EXISTS (SELECT 1 FROM "SupportTicket" p WHERE p."id" = "SupportMessage"."ticketId") AND "internal" = false));

-- SupportTicket (user)
ALTER TABLE "SupportTicket" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SupportTicket" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SupportTicket";
DROP POLICY IF EXISTS tenant_access ON "SupportTicket";
DROP POLICY IF EXISTS tenant_read ON "SupportTicket";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SupportTicket" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SupportTicket";
CREATE POLICY tenant_access ON "SupportTicket" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- TaxRate (reference)
ALTER TABLE "TaxRate" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaxRate" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "TaxRate";
DROP POLICY IF EXISTS tenant_access ON "TaxRate";
DROP POLICY IF EXISTS tenant_read ON "TaxRate";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "TaxRate" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "TaxRate";
CREATE POLICY tenant_read ON "TaxRate" FOR SELECT TO app_tenant USING ("active" = true);

-- TaxRegistration (reference)
ALTER TABLE "TaxRegistration" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TaxRegistration" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "TaxRegistration";
DROP POLICY IF EXISTS tenant_access ON "TaxRegistration";
DROP POLICY IF EXISTS tenant_read ON "TaxRegistration";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "TaxRegistration" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "TaxRegistration";
CREATE POLICY tenant_read ON "TaxRegistration" FOR SELECT TO app_tenant USING ("active" = true);

-- UsageEvent (user)
ALTER TABLE "UsageEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UsageEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "UsageEvent";
DROP POLICY IF EXISTS tenant_access ON "UsageEvent";
DROP POLICY IF EXISTS tenant_read ON "UsageEvent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "UsageEvent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "UsageEvent";
CREATE POLICY tenant_access ON "UsageEvent" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- User (userOwnRow)
ALTER TABLE "User" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "User" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "User";
DROP POLICY IF EXISTS tenant_access ON "User";
DROP POLICY IF EXISTS tenant_read ON "User";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "User" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "User";
CREATE POLICY tenant_read ON "User" FOR SELECT TO app_tenant USING ("id" = app_current_user_id());
CREATE POLICY tenant_update ON "User" FOR UPDATE TO app_tenant USING ("id" = app_current_user_id()) WITH CHECK ("id" = app_current_user_id());
REVOKE INSERT, UPDATE, DELETE ON "User" FROM app_tenant;
GRANT UPDATE ("fullName", "phone", "city", "country", "headline", "linkedinUrl", "portfolioUrl", "workAuth", "onboardedAt", "updatedAt") ON "User" TO app_tenant;

-- UserIdentity (user)
ALTER TABLE "UserIdentity" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "UserIdentity" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "UserIdentity";
DROP POLICY IF EXISTS tenant_access ON "UserIdentity";
DROP POLICY IF EXISTS tenant_read ON "UserIdentity";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "UserIdentity" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "UserIdentity";
CREATE POLICY tenant_access ON "UserIdentity" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- WebhookDelivery (viaParent)
ALTER TABLE "WebhookDelivery" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookDelivery" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "WebhookDelivery";
DROP POLICY IF EXISTS tenant_access ON "WebhookDelivery";
DROP POLICY IF EXISTS tenant_read ON "WebhookDelivery";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "WebhookDelivery" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "WebhookDelivery";
CREATE POLICY tenant_access ON "WebhookDelivery" TO app_tenant USING (EXISTS (SELECT 1 FROM "WebhookEndpoint" p WHERE p."id" = "WebhookDelivery"."endpointId")) WITH CHECK (EXISTS (SELECT 1 FROM "WebhookEndpoint" p WHERE p."id" = "WebhookDelivery"."endpointId"));

-- WebhookEndpoint (user)
ALTER TABLE "WebhookEndpoint" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEndpoint" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "WebhookEndpoint";
DROP POLICY IF EXISTS tenant_access ON "WebhookEndpoint";
DROP POLICY IF EXISTS tenant_read ON "WebhookEndpoint";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "WebhookEndpoint" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "WebhookEndpoint";
CREATE POLICY tenant_access ON "WebhookEndpoint" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- WebhookEvent (system)
ALTER TABLE "WebhookEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "WebhookEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "WebhookEvent";
DROP POLICY IF EXISTS tenant_access ON "WebhookEvent";
DROP POLICY IF EXISTS tenant_read ON "WebhookEvent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "WebhookEvent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "WebhookEvent";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- ---------------------------------------------------------------------------
-- 4. Managed-PostgreSQL hygiene. Supabase exposes the public schema over its
--    REST gateway to the anon and authenticated roles, with default grants on
--    new tables. Nothing in this application is served that way, so where
--    those roles exist their access is revoked outright. RLS being enabled
--    everywhere above already denies them (no policy names them); this makes
--    the intent explicit rather than incidental.
-- ---------------------------------------------------------------------------
DO $$
DECLARE r text;
BEGIN
  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN
      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', r);
      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', r);
      EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', r);
      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM %I', r);
    END IF;
  END LOOP;
END $$;
