-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260905180100_rls_talent_acquisition). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- Disclosure (custom)
ALTER TABLE "Disclosure" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Disclosure" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Disclosure";
DROP POLICY IF EXISTS tenant_access ON "Disclosure";
DROP POLICY IF EXISTS tenant_read ON "Disclosure";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Disclosure" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Disclosure";
CREATE POLICY tenant_access ON "Disclosure" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));
CREATE POLICY tenant_read ON "Disclosure" FOR SELECT TO app_tenant USING (("organizationId" = ANY (app_member_organization_ids()) OR "candidateUserId" = app_current_user_id()));

-- EmployerInterview (org)
ALTER TABLE "EmployerInterview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmployerInterview" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmployerInterview";
DROP POLICY IF EXISTS tenant_access ON "EmployerInterview";
DROP POLICY IF EXISTS tenant_read ON "EmployerInterview";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmployerInterview" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmployerInterview";
CREATE POLICY tenant_access ON "EmployerInterview" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- EmployerNote (org)
ALTER TABLE "EmployerNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmployerNote" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmployerNote";
DROP POLICY IF EXISTS tenant_access ON "EmployerNote";
DROP POLICY IF EXISTS tenant_read ON "EmployerNote";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmployerNote" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmployerNote";
CREATE POLICY tenant_access ON "EmployerNote" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- Offer (org)
ALTER TABLE "Offer" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Offer" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Offer";
DROP POLICY IF EXISTS tenant_access ON "Offer";
DROP POLICY IF EXISTS tenant_read ON "Offer";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Offer" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Offer";
CREATE POLICY tenant_access ON "Offer" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- Requisition (org)
ALTER TABLE "Requisition" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Requisition" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Requisition";
DROP POLICY IF EXISTS tenant_access ON "Requisition";
DROP POLICY IF EXISTS tenant_read ON "Requisition";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Requisition" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Requisition";
CREATE POLICY tenant_access ON "Requisition" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- Submission (org)
ALTER TABLE "Submission" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Submission" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Submission";
DROP POLICY IF EXISTS tenant_access ON "Submission";
DROP POLICY IF EXISTS tenant_read ON "Submission";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Submission" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Submission";
CREATE POLICY tenant_access ON "Submission" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- SubmissionEvent (org)
ALTER TABLE "SubmissionEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "SubmissionEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "SubmissionEvent";
DROP POLICY IF EXISTS tenant_access ON "SubmissionEvent";
DROP POLICY IF EXISTS tenant_read ON "SubmissionEvent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "SubmissionEvent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "SubmissionEvent";
CREATE POLICY tenant_access ON "SubmissionEvent" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- TalentPool (org)
ALTER TABLE "TalentPool" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TalentPool" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "TalentPool";
DROP POLICY IF EXISTS tenant_access ON "TalentPool";
DROP POLICY IF EXISTS tenant_read ON "TalentPool";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "TalentPool" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "TalentPool";
CREATE POLICY tenant_access ON "TalentPool" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));

-- TalentPoolMember (org)
ALTER TABLE "TalentPoolMember" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TalentPoolMember" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "TalentPoolMember";
DROP POLICY IF EXISTS tenant_access ON "TalentPoolMember";
DROP POLICY IF EXISTS tenant_read ON "TalentPoolMember";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "TalentPoolMember" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "TalentPoolMember";
CREATE POLICY tenant_access ON "TalentPoolMember" TO app_tenant USING ("organizationId" = ANY (app_member_organization_ids())) WITH CHECK ("organizationId" = ANY (app_member_organization_ids()));
