-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903130100_rls_provenance_table). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- JobProvenance (reference)
ALTER TABLE "JobProvenance" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "JobProvenance" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "JobProvenance";
DROP POLICY IF EXISTS tenant_access ON "JobProvenance";
DROP POLICY IF EXISTS tenant_read ON "JobProvenance";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "JobProvenance" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "JobProvenance";
CREATE POLICY tenant_read ON "JobProvenance" FOR SELECT TO app_tenant USING (true);
