-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903190100_rls_mailbox_tables). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- CalendarEventRef (user)
ALTER TABLE "CalendarEventRef" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CalendarEventRef" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CalendarEventRef";
DROP POLICY IF EXISTS tenant_access ON "CalendarEventRef";
DROP POLICY IF EXISTS tenant_read ON "CalendarEventRef";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CalendarEventRef" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CalendarEventRef";
CREATE POLICY tenant_access ON "CalendarEventRef" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- EmailMessageRef (user)
ALTER TABLE "EmailMessageRef" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailMessageRef" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmailMessageRef";
DROP POLICY IF EXISTS tenant_access ON "EmailMessageRef";
DROP POLICY IF EXISTS tenant_read ON "EmailMessageRef";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmailMessageRef" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmailMessageRef";
CREATE POLICY tenant_access ON "EmailMessageRef" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- EmailThread (user)
ALTER TABLE "EmailThread" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "EmailThread" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "EmailThread";
DROP POLICY IF EXISTS tenant_access ON "EmailThread";
DROP POLICY IF EXISTS tenant_read ON "EmailThread";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "EmailThread" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "EmailThread";
CREATE POLICY tenant_access ON "EmailThread" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- IntegrationEvent (user)
ALTER TABLE "IntegrationEvent" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "IntegrationEvent" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "IntegrationEvent";
DROP POLICY IF EXISTS tenant_access ON "IntegrationEvent";
DROP POLICY IF EXISTS tenant_read ON "IntegrationEvent";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "IntegrationEvent" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "IntegrationEvent";
CREATE POLICY tenant_access ON "IntegrationEvent" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- MailboxConnection (user)
ALTER TABLE "MailboxConnection" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MailboxConnection" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "MailboxConnection";
DROP POLICY IF EXISTS tenant_access ON "MailboxConnection";
DROP POLICY IF EXISTS tenant_read ON "MailboxConnection";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "MailboxConnection" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "MailboxConnection";
CREATE POLICY tenant_access ON "MailboxConnection" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- MailboxSecret (system)
ALTER TABLE "MailboxSecret" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MailboxSecret" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "MailboxSecret";
DROP POLICY IF EXISTS tenant_access ON "MailboxSecret";
DROP POLICY IF EXISTS tenant_read ON "MailboxSecret";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "MailboxSecret" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "MailboxSecret";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)
