-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903180100_rls_crm_tables). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- ApplicationAssessment (user)
ALTER TABLE "ApplicationAssessment" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApplicationAssessment" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApplicationAssessment";
DROP POLICY IF EXISTS tenant_access ON "ApplicationAssessment";
DROP POLICY IF EXISTS tenant_read ON "ApplicationAssessment";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApplicationAssessment" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApplicationAssessment";
CREATE POLICY tenant_access ON "ApplicationAssessment" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ApplicationContact (user)
ALTER TABLE "ApplicationContact" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApplicationContact" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApplicationContact";
DROP POLICY IF EXISTS tenant_access ON "ApplicationContact";
DROP POLICY IF EXISTS tenant_read ON "ApplicationContact";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApplicationContact" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApplicationContact";
CREATE POLICY tenant_access ON "ApplicationContact" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ApplicationFollowUp (user)
ALTER TABLE "ApplicationFollowUp" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApplicationFollowUp" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApplicationFollowUp";
DROP POLICY IF EXISTS tenant_access ON "ApplicationFollowUp";
DROP POLICY IF EXISTS tenant_read ON "ApplicationFollowUp";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApplicationFollowUp" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApplicationFollowUp";
CREATE POLICY tenant_access ON "ApplicationFollowUp" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ApplicationInterview (user)
ALTER TABLE "ApplicationInterview" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApplicationInterview" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApplicationInterview";
DROP POLICY IF EXISTS tenant_access ON "ApplicationInterview";
DROP POLICY IF EXISTS tenant_read ON "ApplicationInterview";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApplicationInterview" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApplicationInterview";
CREATE POLICY tenant_access ON "ApplicationInterview" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ApplicationNote (user)
ALTER TABLE "ApplicationNote" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApplicationNote" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApplicationNote";
DROP POLICY IF EXISTS tenant_access ON "ApplicationNote";
DROP POLICY IF EXISTS tenant_read ON "ApplicationNote";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApplicationNote" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApplicationNote";
CREATE POLICY tenant_access ON "ApplicationNote" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- ApplicationStatusHistory (user)
ALTER TABLE "ApplicationStatusHistory" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ApplicationStatusHistory" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "ApplicationStatusHistory";
DROP POLICY IF EXISTS tenant_access ON "ApplicationStatusHistory";
DROP POLICY IF EXISTS tenant_read ON "ApplicationStatusHistory";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "ApplicationStatusHistory" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "ApplicationStatusHistory";
CREATE POLICY tenant_access ON "ApplicationStatusHistory" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());
