/**
 * Render src/lib/tenancy/rls-tables.ts to the SQL of the row-level-security
 * migration.
 *
 *   npx tsx scripts/rls/generate-migration.ts > prisma/migrations/<ts>_row_level_security/migration.sql
 *
 * The committed migration is the artefact that runs; this script exists so the
 * migration is reproducible from the classification and so a test can prove
 * the two have not drifted apart (tests/tenancy-isolation.test.ts). The output
 * is deterministic: same input, byte-identical SQL.
 *
 * Everything below is written against the four ADR-0005 amendment findings:
 *
 *   1. Context is read with current_setting(name, TRUE) and compared by
 *      EQUALITY to a real id — never tested for NULL, because a recycled
 *      connection reports the empty string, not NULL.
 *   2. Every table is ENABLE + FORCE, so the owner is bound too.
 *   3. Nothing here interpolates a tenant id; ids arrive at runtime through
 *      set_config($1, $2, TRUE).
 *   4. The system role's access is a named policy in the catalog, not an
 *      accident of being superuser.
 */
import {
  GUC_ORGANIZATION_ID,
  GUC_USER_ID,
  RLS_TABLES,
  TENANT_ROLE,
  type RlsKind,
} from '../../src/lib/tenancy/rls-tables';

const q = (ident: string) => `"${ident.replace(/"/g, '""')}"`;

function usingFor(table: string, rule: RlsKind): { using: string; check: string } | null {
  switch (rule.kind) {
    case 'user':
      return {
        using: `${q(rule.column)} = app_current_user_id()`,
        check: `${q(rule.column)} = app_current_user_id()`,
      };
    case 'userOrOrg': {
      const expr = `(${q(rule.userColumn)} = app_current_user_id() OR ${q(rule.orgColumn)} = ANY (app_member_organization_ids()))`;
      return { using: expr, check: expr };
    }
    case 'org': {
      const expr = `${q(rule.column)} = ANY (app_member_organization_ids())`;
      return { using: expr, check: expr };
    }
    case 'viaParent': {
      const parentKey = rule.parentKey ?? 'id';
      const exists = `EXISTS (SELECT 1 FROM ${q(rule.parent)} p WHERE p.${q(parentKey)} = ${q(table)}.${q(rule.fk)})`;
      const expr = rule.extra ? `(${exists} AND ${rule.extra})` : exists;
      return { using: expr, check: expr };
    }
    case 'custom':
      return { using: rule.using, check: rule.check ?? rule.using };
    case 'reference':
      // SELECT only; the tenant role gets no write policy, so INSERT/UPDATE/
      // DELETE are refused outright (SQLSTATE 42501).
      return { using: rule.where ?? 'true', check: '' };
    case 'system':
      return null;
  }
}

function render(): string {
  const tables = Object.keys(RLS_TABLES).sort();
  const out: string[] = [];
  const emit = (s = '') => out.push(s);

  emit(`-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts.`);
  emit(`-- Do not hand-edit; change the classification and regenerate. A test proves`);
  emit(`-- the committed file matches the generator's output.`);
  emit(`--`);
  emit(`-- Row-level security as the tenancy backstop (ADR-0005, amended).`);
  emit();

  emit(`-- ---------------------------------------------------------------------------`);
  emit(`-- 1. The tenant role. NOLOGIN: it is reached only by SET LOCAL ROLE inside a`);
  emit(`--    transaction that has already established tenant context. NOINHERIT so`);
  emit(`--    it never picks up the migration role's privileges by membership.`);
  emit(`-- ---------------------------------------------------------------------------`);
  emit(`DO $$`);
  emit(`BEGIN`);
  emit(`  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${TENANT_ROLE}') THEN`);
  emit(`    CREATE ROLE ${TENANT_ROLE} NOLOGIN NOINHERIT NOBYPASSRLS NOSUPERUSER NOCREATEDB NOCREATEROLE;`);
  emit(`  END IF;`);
  emit(`  -- The connection role must be a member of the tenant role to SET ROLE to it.`);
  emit(`  EXECUTE format('GRANT ${TENANT_ROLE} TO %I', current_user);`);
  emit(`END $$;`);
  emit();
  emit(`GRANT USAGE ON SCHEMA public TO ${TENANT_ROLE};`);
  emit(`GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO ${TENANT_ROLE};`);
  emit(`GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO ${TENANT_ROLE};`);
  emit(`-- Tables created by later migrations get the same grants; their policies are`);
  emit(`-- still their own migration's job, and the coverage test fails until they exist.`);
  emit(`ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO ${TENANT_ROLE};`);
  emit(`ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT USAGE, SELECT ON SEQUENCES TO ${TENANT_ROLE};`);
  emit();

  emit(`-- ---------------------------------------------------------------------------`);
  emit(`-- 2. Context accessors. STABLE so the planner evaluates them once per`);
  emit(`--    statement. current_setting(name, TRUE) never raises; NULLIF folds the`);
  emit(`--    empty string a recycled connection reports into NULL, and NULL is equal`);
  emit(`--    to nothing, so both "never set" and "set and cleared" match no row.`);
  emit(`-- ---------------------------------------------------------------------------`);
  emit(`CREATE OR REPLACE FUNCTION app_current_user_id() RETURNS text`);
  emit(`  LANGUAGE sql STABLE PARALLEL SAFE`);
  emit(`  AS $$ SELECT NULLIF(current_setting('${GUC_USER_ID}', TRUE), '') $$;`);
  emit();
  emit(`CREATE OR REPLACE FUNCTION app_current_organization_id() RETURNS text`);
  emit(`  LANGUAGE sql STABLE PARALLEL SAFE`);
  emit(`  AS $$ SELECT NULLIF(current_setting('${GUC_ORGANIZATION_ID}', TRUE), '') $$;`);
  emit();
  emit(`-- The organisations the current user is an ACCEPTED, not-removed member of.`);
  emit(`-- SECURITY DEFINER so the Membership read inside it is not itself subject to`);
  emit(`-- the Membership policy, which would otherwise recurse (PostgreSQL refuses a`);
  emit(`-- policy that references its own table). Owned by the migration role, whose`);
  emit(`-- unconditional policy below is what the definer context relies on.`);
  emit(`CREATE OR REPLACE FUNCTION app_member_organization_ids() RETURNS text[]`);
  emit(`  LANGUAGE sql STABLE SECURITY DEFINER`);
  emit(`  SET search_path = public`);
  emit(`  AS $$`);
  emit(`    SELECT COALESCE(array_agg(m."organizationId"), ARRAY[]::text[])`);
  emit(`      FROM "Membership" m`);
  emit(`     WHERE m."userId" = NULLIF(current_setting('${GUC_USER_ID}', TRUE), '')`);
  emit(`       AND m."acceptedAt" IS NOT NULL`);
  emit(`       AND m."removedAt" IS NULL`);
  emit(`  $$;`);
  emit();
  emit(`REVOKE ALL ON FUNCTION app_current_user_id() FROM PUBLIC;`);
  emit(`REVOKE ALL ON FUNCTION app_current_organization_id() FROM PUBLIC;`);
  emit(`REVOKE ALL ON FUNCTION app_member_organization_ids() FROM PUBLIC;`);
  emit(`GRANT EXECUTE ON FUNCTION app_current_user_id() TO ${TENANT_ROLE};`);
  emit(`GRANT EXECUTE ON FUNCTION app_current_organization_id() TO ${TENANT_ROLE};`);
  emit(`GRANT EXECUTE ON FUNCTION app_member_organization_ids() TO ${TENANT_ROLE};`);
  emit();

  emit(`-- ---------------------------------------------------------------------------`);
  emit(`-- 3. Every table: ENABLE and FORCE, then the system role's named policy and`);
  emit(`--    the tenant role's policies. Order matters for nothing; the coverage test`);
  emit(`--    checks the end state, not this script.`);
  emit(`-- ---------------------------------------------------------------------------`);
  for (const table of tables) {
    const rule = RLS_TABLES[table];
    const t = q(table);
    emit(`-- ${table} (${rule.kind})`);
    emit(`ALTER TABLE ${t} ENABLE ROW LEVEL SECURITY;`);
    emit(`ALTER TABLE ${t} FORCE ROW LEVEL SECURITY;`);
    emit(`DROP POLICY IF EXISTS system_full_access ON ${t};`);
    emit(`DROP POLICY IF EXISTS tenant_access ON ${t};`);
    emit(`DROP POLICY IF EXISTS tenant_read ON ${t};`);
    emit(`DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON ${t.replace(/'/g, "''")} TO %I USING (true) WITH CHECK (true)', current_user); END $$;`);
    const p = usingFor(table, rule);
    if (p === null) {
      emit(`-- (no tenant policy: a forced table with no policy for ${TENANT_ROLE} denies every command)`);
    } else if (rule.kind === 'reference') {
      emit(`CREATE POLICY tenant_read ON ${t} FOR SELECT TO ${TENANT_ROLE} USING (${p.using});`);
    } else {
      emit(`CREATE POLICY tenant_access ON ${t} TO ${TENANT_ROLE} USING (${p.using}) WITH CHECK (${p.check});`);
    }
    emit();
  }

  emit(`-- ---------------------------------------------------------------------------`);
  emit(`-- 4. Managed-PostgreSQL hygiene. Supabase exposes the public schema over its`);
  emit(`--    REST gateway to the anon and authenticated roles, with default grants on`);
  emit(`--    new tables. Nothing in this application is served that way, so where`);
  emit(`--    those roles exist their access is revoked outright. RLS being enabled`);
  emit(`--    everywhere above already denies them (no policy names them); this makes`);
  emit(`--    the intent explicit rather than incidental.`);
  emit(`-- ---------------------------------------------------------------------------`);
  emit(`DO $$`);
  emit(`DECLARE r text;`);
  emit(`BEGIN`);
  emit(`  FOREACH r IN ARRAY ARRAY['anon', 'authenticated'] LOOP`);
  emit(`    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = r) THEN`);
  emit(`      EXECUTE format('REVOKE ALL ON ALL TABLES IN SCHEMA public FROM %I', r);`);
  emit(`      EXECUTE format('REVOKE ALL ON ALL SEQUENCES IN SCHEMA public FROM %I', r);`);
  emit(`      EXECUTE format('REVOKE ALL ON ALL FUNCTIONS IN SCHEMA public FROM %I', r);`);
  emit(`      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON TABLES FROM %I', r);`);
  emit(`      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON SEQUENCES FROM %I', r);`);
  emit(`      EXECUTE format('ALTER DEFAULT PRIVILEGES IN SCHEMA public REVOKE ALL ON FUNCTIONS FROM %I', r);`);
  emit(`    END IF;`);
  emit(`  END LOOP;`);
  emit(`END $$;`);
  emit();
  return out.join('\n');
}

process.stdout.write(render());
