-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260905140100_rls_career_graph). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- CareerPlan (user)
ALTER TABLE "CareerPlan" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CareerPlan" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CareerPlan";
DROP POLICY IF EXISTS tenant_access ON "CareerPlan";
DROP POLICY IF EXISTS tenant_read ON "CareerPlan";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CareerPlan" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CareerPlan";
CREATE POLICY tenant_access ON "CareerPlan" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CareerPlanMilestone (user)
ALTER TABLE "CareerPlanMilestone" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CareerPlanMilestone" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CareerPlanMilestone";
DROP POLICY IF EXISTS tenant_access ON "CareerPlanMilestone";
DROP POLICY IF EXISTS tenant_read ON "CareerPlanMilestone";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CareerPlanMilestone" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CareerPlanMilestone";
CREATE POLICY tenant_access ON "CareerPlanMilestone" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- Credential (reference)
ALTER TABLE "Credential" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Credential" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "Credential";
DROP POLICY IF EXISTS tenant_access ON "Credential";
DROP POLICY IF EXISTS tenant_read ON "Credential";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "Credential" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "Credential";
CREATE POLICY tenant_read ON "Credential" FOR SELECT TO app_tenant USING (true);

-- CredentialSkill (reference)
ALTER TABLE "CredentialSkill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CredentialSkill" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CredentialSkill";
DROP POLICY IF EXISTS tenant_access ON "CredentialSkill";
DROP POLICY IF EXISTS tenant_read ON "CredentialSkill";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CredentialSkill" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CredentialSkill";
CREATE POLICY tenant_read ON "CredentialSkill" FOR SELECT TO app_tenant USING (true);

-- LearningOffering (reference)
ALTER TABLE "LearningOffering" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LearningOffering" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "LearningOffering";
DROP POLICY IF EXISTS tenant_access ON "LearningOffering";
DROP POLICY IF EXISTS tenant_read ON "LearningOffering";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "LearningOffering" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "LearningOffering";
CREATE POLICY tenant_read ON "LearningOffering" FOR SELECT TO app_tenant USING (true);

-- LearningProvider (reference)
ALTER TABLE "LearningProvider" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "LearningProvider" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "LearningProvider";
DROP POLICY IF EXISTS tenant_access ON "LearningProvider";
DROP POLICY IF EXISTS tenant_read ON "LearningProvider";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "LearningProvider" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "LearningProvider";
CREATE POLICY tenant_read ON "LearningProvider" FOR SELECT TO app_tenant USING (true);

-- OccupationCredential (reference)
ALTER TABLE "OccupationCredential" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OccupationCredential" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "OccupationCredential";
DROP POLICY IF EXISTS tenant_access ON "OccupationCredential";
DROP POLICY IF EXISTS tenant_read ON "OccupationCredential";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "OccupationCredential" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "OccupationCredential";
CREATE POLICY tenant_read ON "OccupationCredential" FOR SELECT TO app_tenant USING (true);

-- OfferingSkill (reference)
ALTER TABLE "OfferingSkill" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "OfferingSkill" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "OfferingSkill";
DROP POLICY IF EXISTS tenant_access ON "OfferingSkill";
DROP POLICY IF EXISTS tenant_read ON "OfferingSkill";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "OfferingSkill" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "OfferingSkill";
CREATE POLICY tenant_read ON "OfferingSkill" FOR SELECT TO app_tenant USING (true);
