-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903210100_rls_candidate_marts). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- CandidateBenchmarkMart (system)
ALTER TABLE "CandidateBenchmarkMart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CandidateBenchmarkMart" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CandidateBenchmarkMart";
DROP POLICY IF EXISTS tenant_access ON "CandidateBenchmarkMart";
DROP POLICY IF EXISTS tenant_read ON "CandidateBenchmarkMart";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CandidateBenchmarkMart" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CandidateBenchmarkMart";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)

-- CandidateMatchMart (user)
ALTER TABLE "CandidateMatchMart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CandidateMatchMart" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CandidateMatchMart";
DROP POLICY IF EXISTS tenant_access ON "CandidateMatchMart";
DROP POLICY IF EXISTS tenant_read ON "CandidateMatchMart";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CandidateMatchMart" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CandidateMatchMart";
CREATE POLICY tenant_access ON "CandidateMatchMart" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- CandidateOutcomeMart (user)
ALTER TABLE "CandidateOutcomeMart" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "CandidateOutcomeMart" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "CandidateOutcomeMart";
DROP POLICY IF EXISTS tenant_access ON "CandidateOutcomeMart";
DROP POLICY IF EXISTS tenant_read ON "CandidateOutcomeMart";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "CandidateOutcomeMart" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "CandidateOutcomeMart";
CREATE POLICY tenant_access ON "CandidateOutcomeMart" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());
