-- GENERATED by scripts/rls/generate-migration.ts from src/lib/tenancy/rls-tables.ts
-- (manifest: 20260903160100_rls_matching_tables). Do not hand-edit; change the classification
-- and regenerate. A test proves every committed RLS migration matches its manifest.
--
-- Row-level security as the tenancy backstop (ADR-0005, amended).

-- ---------------------------------------------------------------------------
-- 3. Every table: ENABLE and FORCE, then the system role's named policy and
--    the tenant role's policies. Order matters for nothing; the coverage test
--    checks the end state, not this script.
--
--    The system policy is bound to the role that RUNS THIS MIGRATION
--    (current_user). DATABASE_URL must therefore authenticate as the same
--    role as DIRECT_URL: with FORCE on every table, a different application
--    login role would have no policy and every system-client query would
--    return nothing. The tenancy suite asserts this on whatever database it
--    runs against. (Supabase's service_role keeps BYPASSRLS by design; its
--    key is a secret this application never holds.)
-- ---------------------------------------------------------------------------
-- MatchDimension (user)
ALTER TABLE "MatchDimension" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchDimension" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "MatchDimension";
DROP POLICY IF EXISTS tenant_access ON "MatchDimension";
DROP POLICY IF EXISTS tenant_read ON "MatchDimension";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "MatchDimension" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "MatchDimension";
CREATE POLICY tenant_access ON "MatchDimension" TO app_tenant USING ("userId" = app_current_user_id()) WITH CHECK ("userId" = app_current_user_id());

-- MatchWeightVersion (system)
ALTER TABLE "MatchWeightVersion" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "MatchWeightVersion" FORCE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS system_full_access ON "MatchWeightVersion";
DROP POLICY IF EXISTS tenant_access ON "MatchWeightVersion";
DROP POLICY IF EXISTS tenant_read ON "MatchWeightVersion";
DO $$ BEGIN EXECUTE format('CREATE POLICY system_full_access ON "MatchWeightVersion" TO %I USING (true) WITH CHECK (true)', current_user); END $$;
DROP POLICY IF EXISTS tenant_update ON "MatchWeightVersion";
-- (no tenant policy: a forced table with no policy for app_tenant denies every command)
